#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import json
import sys
import os
import urllib.request
import re
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 0
VERSIONS = [
    "GAEJ01_00",  # 0
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--ninja",
    metavar="BINARY",
    type=Path,
    help="path to ninja binary (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--warn",
    dest="warn",
    type=str,
    choices=["all", "off", "error"],
    help="how to handle warnings",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.ninja_path = args.ninja
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-2"
config.compilers_tag = "20251118"
config.dtk_tag = "v1.8.3"
config.objdiff_tag = "v3.6.1"
config.sjiswrap_tag = "v1.2.2"
config.wibo_tag = "1.0.3"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    # Needed for .incbin assets generated by dtk extract.
    f"-I build/{config.version}/bin/assets",
    f"--defsym BUILD_VERSION={version_num}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
]
if args.debug:
    config.ldflags.append("-g")  # Or -gdwarf-2 for Wii linkers
if args.map:
    config.ldflags.append("-mapunused")
    # config.ldflags.append("-listclosure") # For Wii linkers

# Use for any additional files that should cause a re-configure when modified
config.reconfig_deps = []

# Optional numeric ID for decomp.me preset
# Can be overridden in libraries or objects
config.scratch_preset_id = None

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
cflags_base = [
    # Platform Definitions
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    # Multibyte Definitions
    "-multibyte",
    "-char unsigned",
    # Gekko Specific Definitions
    "-fp hardware",
    "-Cpp_exceptions off",
    '-pragma "cats off"',
    # Default compiler flags (turn off if needed)
    # "-W all",
    # "-O4,p",
    # "-inline auto",
    '-pragma "warn_notinlined off"',
    # Helpful linker flags
    "-maxerrors 1",
    "-nosyspath",
    # dtk-specific includes
    "-i include",
    "-i include/dolphin",
    "-i include/libc",
    # "-i src/static/dolphin",
    f"-i build/{config.version}/include",
    f"-DVERSION={version_num}",
]

# Debug flags
if args.debug:
    # Or -sym dwarf-2 for Wii compilers
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.append("-DNDEBUG=1")

# Warning flags
if args.warn == "all":
    cflags_base.append("-W all")
elif args.warn == "off":
    cflags_base.append("-W off")
elif args.warn == "error":
    cflags_base.append("-W error")

cflags_common = [
    # Needed for N64 SDK
    "-d _LANGUAGE_C",
    "-d F3DEX_GBI_2",
    # Project-specific stuff
    "-d MUST_MATCH",
]

# DOL flags
cflags_static = [
    *cflags_base,
    *cflags_common,
    "-O4,s",
]

# Metrowerks library flags
cflags_runtime = [
    *cflags_base,
    "-O4,p",
    "-inline all",
]

# REL flags
cflags_rel = [
    *cflags_base,
    *cflags_common,
    "-O4,s",
    "-inline off",
    "-sdata 0",
    "-sdata2 0",
    "-requireprotos",
    "-sym on",
]

config.sdk_linker_version = "GC/1.3.2"
config.linker_version = "GC/1.3.2"


# Helper function for Dolphin libraries
def DolphinLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.2.5n",
        "cflags": [*cflags_runtime, "-char signed"],
        "progress_category": "sdk",
        "src_dir": "src/static",
        "objects": objects,
    }


# Helper function for REL script objects
def Rel(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": cflags_rel,
        "progress_category": "game",
        "objects": objects,
}


def JSystemLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": [*cflags_base, "-O4,p", "-inline auto", "-RTTI on", "-enum int", "-char signed", "-sym on"],
        "progress_category": "jsystem",
        "src_dir": "src/static",
        "objects": objects,
    }


Matching = True                   # Object matches and should be linked
NonMatching = False               # Object does not match and should not be linked
Equivalent = config.non_matching  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


config.warn_missing_config = True
config.warn_missing_source = False
config.libs = [
    JSystemLib(
        "J2DGraph",
        [
            Object(Matching, "JSystem/J2DGraph/J2DGrafContext.cpp"),
            Object(Matching, "JSystem/J2DGraph/J2DOrthoGraph.cpp"),
        ],
    ),
    JSystemLib(
        "JFramework",
        [
            Object(NonMatching, "JSystem/JFramework/JFWDisplay.cpp"),
            Object(Matching, "JSystem/JFramework/JFWSystem.cpp"),
        ],
    ),
    JSystemLib(
        "JGadget",
        [
            Object(Matching, "JSystem/JGadget/linklist.cpp"),
        ],
    ),
    JSystemLib(
        "JKernel",
        [
            Object(NonMatching, "JSystem/JKernel/JKRAram.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramBlock.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramHeap.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramPiece.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramStream.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRArchivePri.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRArchivePub.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRCompArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDecomp.cpp"),
            Object(Matching, "JSystem/JKernel/JKRDisposer.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdAramRipper.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdFile.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdRipper.cpp"),
            Object(Matching, "JSystem/JKernel/JKRExpHeap.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRFileFinder.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRFileLoader.cpp"),
            Object(Equivalent, "JSystem/JKernel/JKRHeap.cpp"), # Maybe need PCH for this?
            Object(NonMatching, "JSystem/JKernel/JKRMemArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRThread.cpp"),
        ],
    ),
    JSystemLib(
        "JSupport",
        [
            
            Object(Matching, "JSystem/JSupport/JSUFileStream.cpp"),
            Object(Matching, "JSystem/JSupport/JSUInputStream.cpp"),
            Object(Matching, "JSystem/JSupport/JSUList.cpp"),
        ],
    ),
    JSystemLib(
        "JUtility",
        [
            Object(NonMatching, "JSystem/JUtility/JUTAssert.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTConsole.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTDbPrint.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTDirectFile.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTDirectPrint.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTException.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTFader.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTFont.cpp"),
            Object(Matching, "JSystem/JUtility/JUTFontData_Ascfont_fix12.s"),
            Object(NonMatching, "JSystem/JUtility/JUTGamePad.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTGraphFifo.cpp"),
            Object(Matching, "JSystem/JUtility/JUTProcBar.cpp"),
            Object(Matching, "JSystem/JUtility/JUTResFont.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTVideo.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTXfb.cpp"),
            Object(Matching, "JSystem/JUtility/JUTSDDrive.cpp"),
            Object(Matching, "JSystem/JUtility/JUTSDFile.cpp"),
            Object(Matching, "JSystem/JUtility/EXIBios.c", mw_version="GC/1.2.5n", cflags=[*cflags_base, "-O3,p", "-inline all"]),
            Object(NonMatching, "JSystem/JUtility/JUTTiff.cpp", mw_version="GC/1.3"),
        ],
    ),
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.sdk_linker_version,
        "cflags": [*cflags_runtime, "-inline auto,deferred", "-use_lmw_stmw on", "-char signed", "-fp_contract on"],
        "progress_category": "sdk",
        "src_dir": "src/static",
        "objects": [
            Object(Matching, "Runtime.PPCEABI.H/__va_arg.c"),
            Object(Matching, "Runtime.PPCEABI.H/global_destructor_chain.c"),
            Object(Matching, "Runtime.PPCEABI.H/CPlusLibPPC.cp"),
            Object(Matching, "Runtime.PPCEABI.H/NMWException.cp"),
            Object(Matching, "Runtime.PPCEABI.H/ptmf.c"),
            Object(Matching, "Runtime.PPCEABI.H/runtime.c"),
            Object(Matching, "Runtime.PPCEABI.H/__init_cpp_exceptions.cpp"),
            Object(Matching, "Runtime.PPCEABI.H/Gecko_ExceptionPPC.cp"),
            Object(Matching, "Runtime.PPCEABI.H/__mem.c"),
        ],
    },
    {
        "lib": "Famicom",
        "mw_version": "GC/1.3.2",
        "cflags": [
            *cflags_static,
            "-inline off",
            "-sdata 0",
            "-sdata2 0",
            "-sym on",
        ],
        "progress_category": "famicom",
        "src_dir": "src/static",
        "objects": [
            Object(Matching, "Famicom/ks_nes_core.cpp"),
            Object(NonMatching, "Famicom/ks_nes_draw.cpp"),
            Object(Equivalent, "Famicom/famicom.cpp"), # std::strstr appears too early in splits
            Object(Matching, "Famicom/famicom_nesinfo.cpp"),
        ],
    },
    {
        "lib": "libforest",
        "mw_version": config.linker_version,
        "cflags": cflags_static,
        "progress_category": "library",
        "src_dir": "src/static",
        "objects": [
            Object(Equivalent, "libforest/emu64/emu64.c", extra_cflags=["-lang=c++", "-O4,p", "-inline off", "-sym on"]),
            # Object(Matching, "libforest/osreport.c"),
            # Object(Matching, "libforest/fault.c"),
            # Object(Matching, "libforest/ReconfigBATs.c"),
        ],
    },
    Rel(
        "system",
        [
            Object(Matching, "system/sys_dynamic.c"),
            Object(Matching, "system/sys_math.c"),
            Object(Matching, "system/sys_math3d.c"),
            Object(Matching, "system/sys_math_atan.c"),
            Object(Matching, "system/sys_matrix.c"),
            Object(Matching, "system/sys_romcheck.c"),
            Object(Matching, "system/sys_stacks.c"),
            Object(Matching, "system/sys_ucode.c"),
            Object(Matching, "system/sys_vimgr.c"),
        ],
    ),
    Rel(
        "foresta",
        [
            Object(Matching, "audio.c"),
            Object(NonMatching, "c_keyframe.c"),
            Object(Matching, "ev_cherry_manager.c"),
            Object(Matching, "evw_anime.c"),
            Object(Matching, "executor.c"),
            Object(NonMatching, "f_furniture.c"),
            Object(NonMatching, "famicom_emu.c"),
            Object(Matching, "first_game.c"),
            Object(Matching, "game.c"),
            Object(Matching, "gamealloc.c"),
            Object(Matching, "gfxalloc.c"),
            Object(Matching, "graph.c"),
            Object(Matching, "irqmgr.c"),
            Object(Matching, "lb_rtc.c"),
            Object(Matching, "lb_reki.c"),
            Object(Matching, "main.c"),
            Object(Matching, "padmgr.c"),
            Object(Matching, "player_select.c"),
            Object(Matching, "PreRender.c"),
            Object(Matching, "s_cpak.c"),
            Object(Matching, "reload_data.c"),
            Object(Matching, "save_menu.c"),
            Object(Matching, "second_game.c"),
            Object(Matching, "THA_GA.c"),
            Object(Matching, "TwoHeadArena.c"),
            Object(Matching, "zurumode.c"),
        ],
    ),
        Rel(
        "actor",
        [
            Object(NonMatching, "actor/ac_airplane.c"),
            Object(NonMatching, "actor/ac_animal_logo.c"),
            Object(NonMatching, "actor/ac_ant.c"),
            Object(NonMatching, "actor/ac_aprilfool_control.c"),
            Object(NonMatching, "actor/ac_arrange_ftr.c"),
            Object(NonMatching, "actor/ac_arrange_room.c"),
            Object(NonMatching, "actor/ac_ball.c"),
            Object(NonMatching, "actor/ac_balloon.c"),
            Object(NonMatching, "actor/ac_bee.c"),
            Object(NonMatching, "actor/ac_birth_control.c"),
            Object(NonMatching, "actor/ac_boat.c"),
            Object(NonMatching, "actor/ac_boat_demo.c"),
            Object(NonMatching, "actor/ac_boxManager.c"),
            Object(NonMatching, "actor/ac_boxMove.c"),
            Object(NonMatching, "actor/ac_boxTrick01.c"),
            Object(NonMatching, "actor/ac_br_shop.c"),
            Object(NonMatching, "actor/ac_bridge_a.c"),
            Object(NonMatching, "actor/ac_broker_design.c"),
            Object(NonMatching, "actor/ac_buggy.c"),
            Object(NonMatching, "actor/ac_conveni.c"),
            Object(NonMatching, "actor/ac_cottage.c"),
            Object(NonMatching, "actor/ac_count02.c"),
            Object(NonMatching, "actor/ac_countdown.c"),
            Object(NonMatching, "actor/ac_depart.c"),
            Object(NonMatching, "actor/ac_douzou.c"),
            Object(NonMatching, "actor/ac_dummy.c"),
            Object(NonMatching, "actor/ac_dump.c"),
            Object(NonMatching, "actor/ac_effectbg.c"),
            Object(NonMatching, "actor/ac_event_manager.c"),
            Object(NonMatching, "actor/ac_fallS.c"),
            Object(NonMatching, "actor/ac_fallSESW.c"),
            Object(NonMatching, "actor/ac_field_draw.c"),
            Object(NonMatching, "actor/ac_fieldm_draw.c"),
            Object(NonMatching, "actor/ac_flag.c"),
            Object(NonMatching, "actor/ac_fuusen.c"),
            Object(NonMatching, "actor/ac_garagara.c"),
            Object(NonMatching, "actor/ac_ghog.c"),
            Object(NonMatching, "actor/ac_goza.c"),
            Object(NonMatching, "actor/ac_groundhog_control.c"),
            Object(NonMatching, "actor/ac_gyo_kage.c"),
            Object(Matching, "actor/ac_gyo_kaseki.c"),
            Object(NonMatching, "actor/ac_gyo_release.c"),
            Object(Matching, "actor/ac_gyo_test.c"),
            Object(NonMatching, "actor/ac_gyoei.c"),
            Object(NonMatching, "actor/ac_handOverItem.c"),
            Object(NonMatching, "actor/ac_haniwa.c"),
            Object(NonMatching, "actor/ac_hatumode_control.c"),
            Object(NonMatching, "actor/ac_house.c"),
            Object(NonMatching, "actor/ac_house_clock.c"),
            Object(NonMatching, "actor/ac_house_goki.c"),
            Object(NonMatching, "actor/ac_htable.c"),
            Object(NonMatching, "actor/ac_ins_amenbo.c"),
            Object(Matching, "actor/ac_ins_batta.c"),
            Object(NonMatching, "actor/ac_ins_chou.c"),
            Object(NonMatching, "actor/ac_ins_dango.c"),
            Object(NonMatching, "actor/ac_ins_goki.c"),
            Object(Matching, "actor/ac_ins_hitodama.c"),
            Object(Matching, "actor/ac_ins_hotaru.c"),
            Object(Matching, "actor/ac_ins_ka.c"),
            Object(Matching, "actor/ac_ins_kabuto.c"),
            Object(Matching, "actor/ac_ins_kera.c"),
            Object(NonMatching, "actor/ac_ins_mino.c"),
            Object(Matching, "actor/ac_ins_semi.c"),
            Object(Matching, "actor/ac_ins_tentou.c"),
            Object(Matching, "actor/ac_ins_tonbo.c"),
            Object(NonMatching, "actor/ac_insect.c"),
            Object(NonMatching, "actor/ac_intro_demo.c"),
            Object(NonMatching, "actor/ac_kago.c"),
            Object(NonMatching, "actor/ac_kamakura.c"),
            Object(NonMatching, "actor/ac_kamakura_indoor.c"),
            Object(NonMatching, "actor/ac_koinobori.c"),
            Object(NonMatching, "actor/ac_lighthouse_switch.c"),
            Object(NonMatching, "actor/ac_lotus.c"),
            Object(NonMatching, "actor/ac_mailbox.c"),
            Object(NonMatching, "actor/ac_mbg.c"),
            Object(NonMatching, "actor/ac_mikanbox.c"),
            Object(NonMatching, "actor/ac_mikuji.c"),
            Object(NonMatching, "actor/ac_misin.c"),
            Object(NonMatching, "actor/ac_mscore_control.c"),
            Object(NonMatching, "actor/ac_mural.c"),
            Object(NonMatching, "actor/ac_museum.c"),
            Object(NonMatching, "actor/ac_museum_fish.c"),
            Object(NonMatching, "actor/ac_museum_fossil.c"),
            Object(NonMatching, "actor/ac_museum_indoor.c"),
            Object(NonMatching, "actor/ac_museum_insect.c"),
            Object(NonMatching, "actor/ac_museum_picture.c"),
            Object(NonMatching, "actor/ac_my_house.c"),
            Object(NonMatching, "actor/ac_my_indoor.c"),
            Object(NonMatching, "actor/ac_my_room.c"),
            Object(NonMatching, "actor/ac_nameplate.c"),
            Object(NonMatching, "actor/ac_needlework_indoor.c"),
            Object(NonMatching, "actor/ac_needlework_shop.c"),
            Object(NonMatching, "actor/ac_police_box.c"),
            Object(NonMatching, "actor/ac_post_office.c"),
            Object(NonMatching, "actor/ac_present_demo.c"),
            Object(NonMatching, "actor/ac_psnowman.c"),
            Object(NonMatching, "actor/ac_pterminal.c"),
            Object(NonMatching, "actor/ac_quest_manager.c"),
            Object(NonMatching, "actor/ac_quest_talk_fj_init.c"),
            Object(NonMatching, "actor/ac_quest_talk_greeting.c"),
            Object(NonMatching, "actor/ac_quest_talk_init.c"),
            Object(NonMatching, "actor/ac_quest_talk_island.c"),
            Object(NonMatching, "actor/ac_quest_talk_normal_init.c"),
            Object(NonMatching, "actor/ac_radio.c"),
            Object(NonMatching, "actor/ac_reserve.c"),
            Object(NonMatching, "actor/ac_reset_demo.c"),
            Object(NonMatching, "actor/ac_ride_off_demo.c"),
            Object(NonMatching, "actor/ac_rope.c"),
            Object(NonMatching, "actor/ac_s_car.c"),
            Object(NonMatching, "actor/ac_sample.c"),
            Object(NonMatching, "actor/ac_set_manager.c"),
            Object(NonMatching, "actor/ac_set_npc_manager.c"),
            Object(NonMatching, "actor/ac_set_ovl_gyoei.c"),
            Object(NonMatching, "actor/ac_set_ovl_insect.c"),
            Object(NonMatching, "actor/ac_shop.c"),
            Object(NonMatching, "actor/ac_shop_design.c"),
            Object(NonMatching, "actor/ac_shop_goods.c"),
            Object(NonMatching, "actor/ac_shop_indoor.c"),
            Object(NonMatching, "actor/ac_shop_level.c"),
            Object(NonMatching, "actor/ac_shop_manekin.c"),
            Object(NonMatching, "actor/ac_shop_umbrella.c"),
            Object(NonMatching, "actor/ac_shrine.c"),
            Object(NonMatching, "actor/ac_sign.c"),
            Object(NonMatching, "actor/ac_snowman.c"),
            Object(NonMatching, "actor/ac_station.c"),
            Object(NonMatching, "actor/ac_structure.c"),
            Object(NonMatching, "actor/ac_super.c"),
            Object(NonMatching, "actor/ac_tama.c"),
            Object(NonMatching, "actor/ac_tent.c"),
            Object(NonMatching, "actor/ac_tokyoso_control.c"),
            Object(NonMatching, "actor/ac_tools.c"),
            Object(NonMatching, "actor/ac_toudai.c"),
            Object(NonMatching, "actor/ac_train0.c"),
            Object(NonMatching, "actor/ac_train1.c"),
            Object(NonMatching, "actor/ac_train_door.c"),
            Object(NonMatching, "actor/ac_train_window.c"),
            Object(NonMatching, "actor/ac_tukimi.c"),
            Object(NonMatching, "actor/ac_tunahiki_control.c"),
            Object(NonMatching, "actor/ac_turi.c"),
            Object(NonMatching, "actor/ac_uki.c"),
            Object(NonMatching, "actor/ac_weather.c"),
            Object(NonMatching, "actor/ac_weather_fine.c"),
            Object(NonMatching, "actor/ac_weather_leaf.c"),
            Object(NonMatching, "actor/ac_weather_rain.c"),
            Object(NonMatching, "actor/ac_weather_sakura.c"),
            Object(NonMatching, "actor/ac_weather_snow.c"),
            Object(NonMatching, "actor/ac_windmill.c"),
            Object(NonMatching, "actor/ac_yatai.c"),
        ],
    ),
    Rel(
        "actor_npc",
        [
            Object(NonMatching, "actor/npc/ac_countdown_npc0.c"),
            Object(NonMatching, "actor/npc/ac_countdown_npc1.c"),
            Object(NonMatching, "actor/npc/ac_go_home_npc.c"),
            Object(NonMatching, "actor/npc/ac_groundhog_npc0.c"),
            Object(NonMatching, "actor/npc/ac_halloween_npc.c"),
            Object(NonMatching, "actor/npc/ac_hanabi_npc0.c"),
            Object(NonMatching, "actor/npc/ac_hanabi_npc1.c"),
            Object(NonMatching, "actor/npc/ac_hanami_npc0.c"),
            Object(NonMatching, "actor/npc/ac_hanami_npc1.c"),
            Object(NonMatching, "actor/npc/ac_harvest_npc0.c"),
            Object(NonMatching, "actor/npc/ac_harvest_npc1.c"),
            Object(NonMatching, "actor/npc/ac_hatumode_npc0.c"),
            Object(NonMatching, "actor/npc/ac_kamakura_npc0.c"),
            Object(NonMatching, "actor/npc/ac_normal_npc.c"),
            Object(NonMatching, "actor/npc/ac_npc.c"),
            Object(NonMatching, "actor/npc/ac_npc2.c"),
            Object(NonMatching, "actor/npc/ac_npc_conv_master.c"),
            Object(NonMatching, "actor/npc/ac_npc_curator.c"),
            Object(NonMatching, "actor/npc/ac_npc_depart_master.c"),
            Object(NonMatching, "actor/npc/ac_npc_engineer.c"),
            Object(NonMatching, "actor/npc/ac_npc_guide.c"),
            Object(NonMatching, "actor/npc/ac_npc_guide2.c"),
            Object(NonMatching, "actor/npc/ac_npc_hem.c"),
            Object(NonMatching, "actor/npc/ac_npc_majin.c"),
            Object(NonMatching, "actor/npc/ac_npc_majin2.c"),
            Object(NonMatching, "actor/npc/ac_npc_majin3.c"),
            Object(NonMatching, "actor/npc/ac_npc_majin4.c"),
            Object(NonMatching, "actor/npc/ac_npc_majin5.c"),
            Object(NonMatching, "actor/npc/ac_npc_mamedanuki.c"),
            Object(NonMatching, "actor/npc/ac_npc_mask_cat.c"),
            Object(NonMatching, "actor/npc/ac_npc_mask_cat2.c"),
            Object(NonMatching, "actor/npc/ac_npc_needlework.c"),
            Object(NonMatching, "actor/npc/ac_npc_p_sel.c"),
            Object(NonMatching, "actor/npc/ac_npc_p_sel2.c"),
            Object(NonMatching, "actor/npc/ac_npc_police.c"),
            Object(NonMatching, "actor/npc/ac_npc_police2.c"),
            Object(NonMatching, "actor/npc/ac_npc_post_girl.c"),
            Object(NonMatching, "actor/npc/ac_npc_post_man.c"),
            Object(NonMatching, "actor/npc/ac_npc_rcn_guide.c"),
            Object(NonMatching, "actor/npc/ac_npc_rcn_guide2.c"),
            Object(NonMatching, "actor/npc/ac_npc_restart.c"),
            Object(NonMatching, "actor/npc/ac_npc_rtc.c"),
            Object(NonMatching, "actor/npc/ac_npc_sendo.c"),
            Object(NonMatching, "actor/npc/ac_npc_shasho.c"),
            Object(NonMatching, "actor/npc/ac_npc_shop_master.c"),
            Object(NonMatching, "actor/npc/ac_npc_shop_mastersp.c"),
            Object(NonMatching, "actor/npc/ac_npc_sleep_obaba.c"),
            Object(NonMatching, "actor/npc/ac_npc_soncho.c"),
            Object(NonMatching, "actor/npc/ac_npc_station_master.c"),
            Object(NonMatching, "actor/npc/ac_npc_super_master.c"),
            Object(NonMatching, "actor/npc/ac_npc_totakeke.c"),
            Object(NonMatching, "actor/npc/ac_present_npc.c"),
            Object(NonMatching, "actor/npc/ac_taisou_npc0.c"),
            Object(NonMatching, "actor/npc/ac_tamaire_npc0.c"),
            Object(NonMatching, "actor/npc/ac_tamaire_npc1.c"),
            Object(NonMatching, "actor/npc/ac_tokyoso_npc0.c"),
            Object(NonMatching, "actor/npc/ac_tokyoso_npc1.c"),
            Object(NonMatching, "actor/npc/ac_tukimi_npc0.c"),
            Object(NonMatching, "actor/npc/ac_tukimi_npc1.c"),
            Object(NonMatching, "actor/npc/ac_tunahiki_npc0.c"),
            Object(NonMatching, "actor/npc/ac_tunahiki_npc1.c"),
            Object(NonMatching, "actor/npc/ac_turi_npc0.c"),
        ],
    ),
    Rel(
        "actor_npc_event",
        [
            Object(NonMatching, "actor/npc/event/ac_ev_angler.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_artist.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_broker.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_broker2.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_carpetPeddler.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_castaway.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_designer.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_dokutu.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_dozaemon.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_ghost.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_gypsy.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_kabuPeddler.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_majin.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_miko.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_pumpkin.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_santa.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_soncho.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_soncho2.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_speech_soncho.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_turkey.c"),
            Object(NonMatching, "actor/npc/event/ac_ev_yomise.c"),
        ],
    ),
    Rel(
        "actor_tool",
        [
            Object(NonMatching, "actor/tool/ac_t_anrium1.c"),
            Object(NonMatching, "actor/tool/ac_t_bag1.c"),
            Object(NonMatching, "actor/tool/ac_t_bag2.c"),
            Object(NonMatching, "actor/tool/ac_t_biscus1.c"),
            Object(NonMatching, "actor/tool/ac_t_biscus2.c"),
            Object(NonMatching, "actor/tool/ac_t_biscus3.c"),
            Object(NonMatching, "actor/tool/ac_t_biscus4.c"),
            Object(NonMatching, "actor/tool/ac_t_cobra1.c"),
            Object(NonMatching, "actor/tool/ac_t_cracker.c"),
            Object(NonMatching, "actor/tool/ac_t_flag.c"),
            Object(NonMatching, "actor/tool/ac_t_hanabi.c"),
            Object(NonMatching, "actor/tool/ac_t_hasu1.c"),
            Object(NonMatching, "actor/tool/ac_t_hat1.c"),
            Object(NonMatching, "actor/tool/ac_t_hat2.c"),
            Object(NonMatching, "actor/tool/ac_t_hat3.c"),
            Object(NonMatching, "actor/tool/ac_t_keitai.c"),
            Object(NonMatching, "actor/tool/ac_t_npc_sao.c"),
            Object(NonMatching, "actor/tool/ac_t_pistol.c"),
            Object(NonMatching, "actor/tool/ac_t_rei1.c"),
            Object(NonMatching, "actor/tool/ac_t_rei2.c"),
            Object(NonMatching, "actor/tool/ac_t_tama.c"),
            Object(NonMatching, "actor/tool/ac_t_tumbler.c"),
            Object(NonMatching, "actor/tool/ac_t_umbrella.c"),
            Object(NonMatching, "actor/tool/ac_t_utiwa.c"),
            Object(NonMatching, "actor/tool/ac_t_zinnia1.c"),
            Object(NonMatching, "actor/tool/ac_t_zinnia2.c"),
        ],
    ),
    Rel(
        "bg_item",
        [
            Object(NonMatching, "bg_item/bg_cherry_item.c"),
            Object(NonMatching, "bg_item/bg_item.c"),
            Object(NonMatching, "bg_item/bg_police_item.c"),
            Object(NonMatching, "bg_item/bg_post_item.c"),
            Object(NonMatching, "bg_item/bg_winter_item.c"),
            Object(NonMatching, "bg_item/bg_xmas_item.c"),
        ],
    ),
    Rel(
        "effect",
        [
            Object(Matching, "effect/ef_ami_mizu.c"),
            Object(Matching, "effect/ef_anahikari.c"),
            Object(Matching, "effect/ef_ase.c"),
            Object(Matching, "effect/ef_ase2.c"),
            Object(Matching, "effect/ef_ase_ch.c"),
            Object(Matching, "effect/ef_break_axe.c"),
            Object(Matching, "effect/ef_bubu.c"),
            Object(Matching, "effect/ef_buruburu.c"),
            Object(Matching, "effect/ef_bush_happa.c"),
            Object(Matching, "effect/ef_bush_yuki.c"),
            Object(Matching, "effect/ef_car_blight.c"),
            Object(Matching, "effect/ef_car_light.c"),
            Object(Matching, "effect/ef_clacker.c"),
            Object(Matching, "effect/ef_coin.c"),
            Object(Matching, "effect/ef_dash_asimoto.c"),
            Object(Matching, "effect/ef_dig_hole.c"),
            Object(Matching, "effect/ef_dig_mud.c"),
            Object(Matching, "effect/ef_dig_scoop.c"),
            Object(Matching, "effect/ef_douzou_light.c"),
            Object(Matching, "effect/ef_doyon.c"),
            Object(Matching, "effect/ef_dust.c"),
            Object(Matching, "effect/ef_effect_control.c"),
            Object(Matching, "effect/ef_flash.c"),
            Object(Matching, "effect/ef_footprint.c"),
            Object(Matching, "effect/ef_furo_yuge.c"),
            Object(Matching, "effect/ef_gimonhu.c"),
            Object(Matching, "effect/ef_goki.c"),
            Object(Matching, "effect/ef_ha.c"),
            Object(Matching, "effect/ef_halloween.c"),
            Object(Matching, "effect/ef_halloween_smoke.c"),
            Object(Matching, "effect/ef_hanabi_botan1.c"),
            Object(Matching, "effect/ef_hanabi_botan2.c"),
            Object(Matching, "effect/ef_hanabi_dummy.c"),
            Object(Matching, "effect/ef_hanabi_hoshi.c"),
            Object(Matching, "effect/ef_hanabi_set.c"),
            Object(Matching, "effect/ef_hanabi_switch.c"),
            Object(Matching, "effect/ef_hanabi_yanagi.c"),
            Object(Matching, "effect/ef_hanabira.c"),
            Object(Matching, "effect/ef_hanatiri.c"),
            Object(Matching, "effect/ef_hirameki_den.c"),
            Object(Matching, "effect/ef_hirameki_hikari.c"),
            Object(Matching, "effect/ef_ikigire.c"),
            Object(Matching, "effect/ef_impact_star.c"),
            Object(Matching, "effect/ef_kagu_happa.c"),
            Object(Matching, "effect/ef_kamifubuki.c"),
            Object(Matching, "effect/ef_kangaeru.c"),
            Object(Matching, "effect/ef_kantanhu.c"),
            Object(Matching, "effect/ef_kasamizu.c"),
            Object(Matching, "effect/ef_kasamizutama.c"),
            Object(Matching, "effect/ef_kaze.c"),
            Object(Matching, "effect/ef_kaze_happa.c"),
            Object(Matching, "effect/ef_kigae.c"),
            Object(Matching, "effect/ef_kigae_light.c"),
            Object(Matching, "effect/ef_kikuzu.c"),
            Object(Matching, "effect/ef_killer.c"),
            Object(Matching, "effect/ef_kisha_kemuri.c"),
            Object(Matching, "effect/ef_konpu.c"),
            Object(Matching, "effect/ef_kpun.c"),
            Object(Matching, "effect/ef_kyousou_onpu.c"),
            Object(Matching, "effect/ef_lamp_light.c"),
            Object(Matching, "effect/ef_lovelove.c"),
            Object(Matching, "effect/ef_lovelove2.c"),
            Object(Matching, "effect/ef_lovelove_heart.c"),
            Object(Matching, "effect/ef_make_hem.c"),
            Object(Matching, "effect/ef_mizutama.c"),
            Object(Matching, "effect/ef_motiyuge.c"),
            Object(Matching, "effect/ef_muka.c"),
            Object(Matching, "effect/ef_naku.c"),
            Object(Matching, "effect/ef_namida.c"),
            Object(Matching, "effect/ef_neboke.c"),
            Object(Matching, "effect/ef_neboke_akubi.c"),
            Object(Matching, "effect/ef_neboke_awa.c"),
            Object(Matching, "effect/ef_night13_moon.c"),
            Object(Matching, "effect/ef_night15_moon.c"),
            Object(Matching, "effect/ef_nomi.c"),
            Object(Matching, "effect/ef_ongen.c"),
            Object(Matching, "effect/ef_otikomi.c"),
            Object(Matching, "effect/ef_otosiana.c"),
            Object(Matching, "effect/ef_presentopen.c"),
            Object(Matching, "effect/ef_presentopen_parts.c"),
            Object(Matching, "effect/ef_pun.c"),
            Object(Matching, "effect/ef_pun_sekimen.c"),
            Object(Matching, "effect/ef_pun_yuge.c"),
            Object(Matching, "effect/ef_resetbreak.c"),
            Object(Matching, "effect/ef_resetbreak_dust.c"),
            Object(NonMatching, "effect/ef_resetbreak_parts.c"),
            Object(Matching, "effect/ef_resetbreak_piece.c"),
            Object(Matching, "effect/ef_reset_hole.c"),
            Object(Matching, "effect/ef_room_sunshine.c"),
            Object(Matching, "effect/ef_room_sunshine_minsect.c"),
            Object(Matching, "effect/ef_room_sunshine_museum.c"),
            Object(Matching, "effect/ef_room_sunshine_police.c"),
            Object(Matching, "effect/ef_room_sunshine_posthouse.c"),
            Object(Matching, "effect/ef_sandsplash.c"),
            Object(Matching, "effect/ef_shock.c"),
            Object(Matching, "effect/ef_shooting.c"),
            Object(Matching, "effect/ef_shooting_kira.c"),
            Object(Matching, "effect/ef_shooting_set.c"),
            Object(Matching, "effect/ef_siawase_hana.c"),
            Object(Matching, "effect/ef_siawase_hana_ch.c"),
            Object(Matching, "effect/ef_siawase_hikari.c"),
            Object(Matching, "effect/ef_sibuki.c"),
            Object(Matching, "effect/ef_situren.c"),
            Object(Matching, "effect/ef_slip.c"),
            Object(Matching, "effect/ef_slip_footprint.c"),
            Object(Matching, "effect/ef_soba_yuge.c"),
            Object(Matching, "effect/ef_steam.c"),
            Object(Matching, "effect/ef_string.c"),
            Object(Matching, "effect/ef_suisou_awa.c"),
            Object(Matching, "effect/ef_swing_axe.c"),
            Object(Matching, "effect/ef_swing_net.c"),
            Object(Matching, "effect/ef_swing_rod.c"),
            Object(Matching, "effect/ef_taberu.c"),
            Object(Matching, "effect/ef_takurami.c"),
            Object(Matching, "effect/ef_takurami_kira.c"),
            Object(Matching, "effect/ef_tamaire.c"),
            Object(Matching, "effect/ef_tape.c"),
            Object(Matching, "effect/ef_tent_lamp.c"),
            Object(Matching, "effect/ef_tumble.c"),
            Object(Matching, "effect/ef_tumble_bodyprint.c"),
            Object(Matching, "effect/ef_tumble_dust.c"),
            Object(Matching, "effect/ef_turi_hamon.c"),
            Object(Matching, "effect/ef_turi_hane0.c"),
            Object(Matching, "effect/ef_turi_hane1.c"),
            Object(Matching, "effect/ef_turi_mizu.c"),
            Object(Matching, "effect/ef_turi_suiteki.c"),
            Object(Matching, "effect/ef_turn_asimoto.c"),
            Object(Matching, "effect/ef_turn_footprint.c"),
            Object(Matching, "effect/ef_uranai.c"),
            Object(Matching, "effect/ef_wait_asimoto.c"),
            Object(Matching, "effect/ef_walk_asimoto.c"),
            Object(Matching, "effect/ef_warau.c"),
            Object(Matching, "effect/ef_yajirushi.c"),
            Object(Matching, "effect/ef_young_tree.c"),
            Object(Matching, "effect/ef_yukidama.c"),
            Object(Matching, "effect/ef_yukidaruma.c"),
            Object(Matching, "effect/ef_yukihane.c"),
        ],
    ),
    Rel(
        "game",
        [
            Object(Matching, "game/m_actor.c"), # std::strstr appears too early in splits
            Object(NonMatching, "game/m_actor_dlftbls.c"),
            Object(Matching, "game/m_actor_shadow.c"),
            Object(Matching, "game/m_add_npc.c"),
            Object(NonMatching, "game/m_address_ovl.c"),
            Object(NonMatching, "game/m_all_grow.c"),
            Object(NonMatching, "game/m_all_grow_ovl.c"),
            Object(NonMatching, "game/m_bank_ovl.c"),
            Object(NonMatching, "game/m_banti.c"),
            Object(Matching, "game/m_bg_item.c"),
            Object(NonMatching, "game/m_bg_tex.c"),
            Object(NonMatching, "game/m_bgm.c"),
            Object(NonMatching, "game/m_birthday_ovl.c"),
            Object(NonMatching, "game/m_board_ovl.c"),
            Object(Matching, "game/m_calendar.c"),
            Object(NonMatching, "game/m_calendar_ovl.c"),
            Object(NonMatching, "game/m_camera2.c"),
            Object(NonMatching, "game/m_card.c"),
            Object(NonMatching, "game/m_catalog_ovl.c"),
            Object(NonMatching, "game/m_choice.c"),
            Object(Matching, "game/m_clip.c"),
            Object(NonMatching, "game/m_cockroach.c"),
            Object(Matching, "game/m_collision_bg.c"),
            Object(Matching, "game/m_collision_bg_math.c"),
            Object(Matching, "game/m_collision_obj.c"),
            Object(Matching, "game/m_common_data.c"),
            Object(Matching, "game/m_controller.c"),
            Object(Matching, "game/m_cpak.c"),
            Object(NonMatching, "game/m_cpedit_ovl.c"),
            Object(NonMatching, "game/m_cpmail_ovl.c"),
            Object(NonMatching, "game/m_cporiginal_ovl.c"),
            Object(NonMatching, "game/m_cpwarning_ovl.c"),
            Object(Matching, "game/m_debug.c"),
            Object(Matching, "game/m_debug_display.c"),
            Object(NonMatching, "game/m_debug_hayakawa.c"),
            Object(NonMatching, "game/m_debug_mode.c"),
            Object(Matching, "game/m_demo.c"),
            Object(NonMatching, "game/m_design_ovl.c"),
            Object(Equivalent, "game/m_diary.c"), # matching but needs investigation
            Object(NonMatching, "game/m_diary_ovl.c"),
            Object(NonMatching, "game/m_eappli.c"),
            Object(NonMatching, "game/m_editEndChk_ovl.c"),
            Object(NonMatching, "game/m_editor_ovl.c"),
            Object(NonMatching, "game/m_event.c"),
            Object(NonMatching, "game/m_event_map_npc.c"),
            Object(Matching, "game/m_fbdemo.c"),
            Object(Matching, "game/m_fbdemo_fade.c"),
            Object(Matching, "game/m_fbdemo_triforce.c"),
            Object(Matching, "game/m_fbdemo_wipe1.c"),
            Object(Matching, "game/m_field_assessment.c"),
            Object(Matching, "game/m_field_info.c"),
            Object(NonMatching, "game/m_field_make.c"),
            Object(NonMatching, "game/m_fishrecord.c"),
            Object(NonMatching, "game/m_flashrom.c"),
            Object(NonMatching, "game/m_font.c"),
            Object(Matching, "game/m_fuusen.c"),
            Object(NonMatching, "game/m_game_dlftbls.c"),
            Object(NonMatching, "game/m_gba_ovl.c"),
            Object(NonMatching, "game/m_hand_ovl.c"),
            Object(NonMatching, "game/m_handbill.c"),
            Object(NonMatching, "game/m_haniwaPortrait_ovl.c"),
            Object(NonMatching, "game/m_haniwa_ovl.c"),
            Object(NonMatching, "game/m_hboard_ovl.c"),
            Object(Matching, "game/m_home.c"),
            Object(Matching, "game/m_house.c"),
            Object(Matching, "game/m_huusui_room.c"),
            Object(NonMatching, "game/m_huusui_room_ovl.c"),
            Object(NonMatching, "game/m_inventory_ovl.c"),
            Object(NonMatching, "game/m_island.c"),
            # Object(NonMatching, "game/m_item_debug.c"), # Not present in foresta/splits.txt
            Object(NonMatching, "game/m_item_name.c"),
            Object(Matching, "game/m_kabu_manager.c"),
            Object(NonMatching, "game/m_kankyo.c"),
            Object(Matching, "game/m_land.c"),
            Object(NonMatching, "game/m_ledit_ovl.c"),
            Object(NonMatching, "game/m_lib.c"),
            Object(Matching, "game/m_lights.c"),
            Object(Matching, "game/m_mail.c"),
            Object(Matching, "game/m_mail_check.c"),
            Object(NonMatching, "game/m_mail_check_ovl.c"),
            Object(NonMatching, "game/m_mail_password_check.c"),
            Object(NonMatching, "game/m_mailbox_ovl.c"),
            Object(Matching, "game/m_malloc.c"),
            Object(NonMatching, "game/m_map_ovl.c"),
            Object(Matching, "game/m_mark_room.c"),
            Object(NonMatching, "game/m_mark_room_ovl.c"),
            Object(Matching, "game/m_matching.c"),
            Object(Matching, "game/m_melody.c"),
            Object(Matching, "game/m_monument.c"),
            Object(NonMatching, "game/m_mscore_ovl.c"),
            Object(NonMatching, "game/m_msg.c"),
            Object(Matching, "game/m_museum.c"),
            Object(Matching, "game/m_museum_display.c"),
            Object(Matching, "game/m_mushroom.c"),
            Object(NonMatching, "game/m_music_ovl.c"),
            Object(NonMatching, "game/m_name_table.c"),
            Object(NonMatching, "game/m_needlework.c"),
            Object(NonMatching, "game/m_needlework_ovl.c"),
            Object(NonMatching, "game/m_notice.c"),
            Object(NonMatching, "game/m_notice_ovl.c"),
            Object(NonMatching, "game/m_npc.c"),
            Object(Matching, "game/m_npc_schedule.c"),
            Object(Matching, "game/m_npc_walk.c"),
            Object(Matching, "game/m_olib.c"),
            Object(NonMatching, "game/m_passwordChk_ovl.c"),
            Object(NonMatching, "game/m_passwordMake_ovl.c"),
            Object(Matching, "game/m_pause.c"),
            Object(Matching, "game/m_play.c"),
            Object(NonMatching, "game/m_player.c"),
            Object(NonMatching, "game/m_player_call.c"),
            Object(NonMatching, "game/m_player_lib.c"),
            Object(NonMatching, "game/m_police_box.c"),
            Object(NonMatching, "game/m_post_office.c"),
            Object(Matching, "game/m_prenmi.c"),
            Object(NonMatching, "game/m_private.c"),
            Object(NonMatching, "game/m_quest.c"),
            Object(NonMatching, "game/m_random_field.c"),
            Object(NonMatching, "game/m_random_field_ovl.c"),
            Object(Matching, "game/m_rcp.c"),
            Object(NonMatching, "game/m_repay_ovl.c"),
            Object(NonMatching, "game/m_roll_lib.c"),
            Object(NonMatching, "game/m_room_type.c"),
            Object(NonMatching, "game/m_scene.c"),
            Object(Matching, "game/m_scene_ftr.c"),
            Object(Matching, "game/m_scene_table.c"),
            Object(Matching, "game/m_select.c"),
            Object(NonMatching, "game/m_shop.c"),
            Object(Matching, "game/m_skin_matrix.c"),
            Object(Matching, "game/m_snowman.c"),
            Object(NonMatching, "game/m_soncho.c"),
            Object(NonMatching, "game/m_start_data_init.c"),
            Object(NonMatching, "game/m_string.c"),
            Object(NonMatching, "game/m_submenu.c"),
            Object(NonMatching, "game/m_submenu_ovl.c"),
            Object(NonMatching, "game/m_tag_ovl.c"),
            Object(Matching, "game/m_text.c"),
            Object(Matching, "game/m_time.c"),
            Object(NonMatching, "game/m_timeIn_ovl.c"),
            Object(Matching, "game/m_titledemo.c"),
            Object(Matching, "game/m_trademark.c"),
            Object(Matching, "game/m_train_control.c"),
            Object(Matching, "game/m_vibctl.c"),
            Object(Matching, "game/m_view.c"),
            Object(NonMatching, "game/m_warning_ovl.c"),
            Object(Matching, "game/m_watch_my_step.c"),
        ],
    ),
]


# Define our custom asset processing scripts
config.custom_build_rules = [
    {
        "name": "convert_pal16",
        "command": "$python tools/converters/pal16dis.py $in $out",
        "description": "CONVERT $symbol",
    },
    # We run the script in "scan" mode first to generate a .dd (dyndep) file
    # This allows ninja to understand what files are generated by the script
    {
        "name": "scan_pal16_chunked",
        "command": "$python tools/converters/pal16dis_chunked.py $in $base -s $stamp -d $out",
        "description": "SCAN $symbol",
    },
    {
        "name": "convert_pal16_chunked",
        "command": "$python tools/converters/pal16dis_chunked.py $in $base -s $out",
        "description": "CONVERT $symbol",
    },
    {
        "name": "convert_vtx",
        "command": "$python tools/converters/vtxdis.py $in $out",
        "description": "CONVERT $symbol",
    },
]
config.custom_build_steps = {}

# Grab the specific GameID so we can format our strings properly
version = VERSIONS[version_num]
out_dir = config.build_dir / version


# This generates the build steps needed for preprocessing
def emit_build_rule(asset):
    steps = config.custom_build_steps.setdefault("pre-compile", [])

    match asset.get("custom_type"):
        case None:
            return

        case "pal16":
            steps.append(
                {
                    "rule": "convert_pal16",
                    "inputs": out_dir / "bin" / asset["binary"],
                    "outputs": out_dir / "include" / asset["header"],
                    "variables": {
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/pal16dis.py"),
                }
            )

        case "pal16c":
            # Run the script in scan mode first to generate a .dd file
            input = out_dir / "bin" / asset["binary"]
            out_base = out_dir / "include" / asset["header"]
            dyndep = out_dir / "include" / f"{asset['header']}.dd"
            # We need a stamp file to use as a marker for ninja
            stamp = out_dir / "include" / f"{asset['header']}.stamp"
            steps.append(
                {
                    "rule": "scan_pal16_chunked",
                    "inputs": input,
                    "outputs": dyndep,
                    "variables": {
                        "base": out_base,
                        "stamp": stamp,
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/pal16dis_chunked.py"),
                }
            )
            # Now the script will generate all the dynamic outputs and stamp file
            steps.append(
                {
                    "rule": "convert_pal16_chunked",
                    "inputs": input,
                    "outputs": stamp,
                    "variables": {
                        "base": out_base,
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/pal16dis_chunked.py"),
                    "dyndep": dyndep,
                    "order_only": dyndep,
                }
            )

        case "vtx":
            steps.append(
                {
                    "rule": "convert_vtx",
                    "inputs": out_dir / "bin" / asset["binary"],
                    "outputs": out_dir / "include" / asset["header"],
                    "variables": {
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/vtxdis.py"),
                }
            )

        case _:
            print("Unknown asset type: " + asset["custom_type"])


# Parse the config and create the build rules for all our assets
config_path = out_dir / "config.json"
if config_path.exists():
    config_data = json.load(open(config_path))
    for asset in config_data.get("extract", []):
        emit_build_rule(asset)
    for module in config_data.get("modules", []):
        for asset in module.get("extract", []):
            emit_build_rule(asset)


# Optional callback to adjust link order. This can be used to add, remove, or reorder objects.
# This is called once per module, with the module ID and the current link order.
#
# For example, this adds "dummy.c" to the end of the DOL link order if configured with --non-matching.
# "dummy.c" *must* be configured as a Matching (or Equivalent) object in order to be linked.
def link_order_callback(module_id: int, objects: List[str]) -> List[str]:
    # Don't modify the link order for matching builds
    if not config.non_matching:
        return objects
    if module_id == 0:  # DOL
        return objects + ["dummy.c"]
    return objects


# Uncomment to enable the link order callback.
# config.link_order_callback = link_order_callback


# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    ProgressCategory("game", "Game Code"),
    ProgressCategory("sdk", "SDK Code"),
    ProgressCategory("jsystem", "JSystem"),
    ProgressCategory("famicom", "NES Emulator"),
    ProgressCategory("library", "Library Code"),
]
config.progress_each_module = args.verbose
# Optional extra arguments to `objdiff-cli report generate`
config.progress_report_args = [
    # Marks relocations as mismatching if the target value is different
    # Default is "functionRelocDiffs=none", which is most lenient
    # "--config functionRelocDiffs=data_value",
]

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress information
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
