#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import json
import sys
import os
import urllib.request
import re
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 0
VERSIONS = [
    "GAEJ01_00",  # 0
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--ninja",
    metavar="BINARY",
    type=Path,
    help="path to ninja binary (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--warn",
    dest="warn",
    type=str,
    choices=["all", "off", "error"],
    help="how to handle warnings",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.ninja_path = args.ninja
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-2"
config.compilers_tag = "20251118"
config.dtk_tag = "v1.8.3"
config.objdiff_tag = "v3.6.1"
config.sjiswrap_tag = "v1.2.2"
config.wibo_tag = "1.0.3"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    # Needed for .incbin assets generated by dtk extract.
    f"-I build/{config.version}/bin/assets",
    f"--defsym BUILD_VERSION={version_num}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
]
if args.debug:
    config.ldflags.append("-g")  # Or -gdwarf-2 for Wii linkers
if args.map:
    config.ldflags.append("-mapunused")
    # config.ldflags.append("-listclosure") # For Wii linkers

# Use for any additional files that should cause a re-configure when modified
config.reconfig_deps = []

# Optional numeric ID for decomp.me preset
# Can be overridden in libraries or objects
config.scratch_preset_id = None

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
cflags_base = [
    # Platform Definitions
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    # Multibyte Definitions
    "-multibyte",
    "-char unsigned",
    # Gekko Specific Definitions
    "-fp hardware",
    "-Cpp_exceptions off",
    '-pragma "cats off"',
    # Default compiler flags (turn off if needed)
    # "-W all",
    # "-O4,p",
    # "-inline auto",
    '-pragma "warn_notinlined off"',
    # Helpful linker flags
    "-maxerrors 1",
    "-nosyspath",
    # dtk-specific includes
    "-i include",
    "-i include/dolphin",
    "-i include/libc",
    # "-i src/static/dolphin",
    f"-i build/{config.version}/include",
    f"-DVERSION={version_num}",
]

# Debug flags
if args.debug:
    # Or -sym dwarf-2 for Wii compilers
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.append("-DNDEBUG=1")

# Warning flags
if args.warn == "all":
    cflags_base.append("-W all")
elif args.warn == "off":
    cflags_base.append("-W off")
elif args.warn == "error":
    cflags_base.append("-W error")

cflags_common = [
    # Needed for N64 SDK
    "-d _LANGUAGE_C",
    "-d F3DEX_GBI_2",
    # Project-specific stuff
    "-d MUST_MATCH",
]

# DOL flags
cflags_static = [
    *cflags_base,
    *cflags_common,
    "-O4,s",
]

# Metrowerks library flags
cflags_runtime = [
    *cflags_base,
    "-O4,p",
    "-inline all",
]

# REL flags
cflags_rel = [
    *cflags_base,
    *cflags_common,
    "-O4,s",
    "-inline off",
    "-sdata 0",
    "-sdata2 0",
    "-requireprotos",
    "-sym on",
]

config.sdk_linker_version = "GC/1.3.2"
config.linker_version = "GC/1.3.2"


# Helper function for Dolphin libraries
def DolphinLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.2.5n",
        "cflags": [*cflags_runtime, "-char signed"],
        "progress_category": "sdk",
        "src_dir": "src/static",
        "objects": objects,
    }


# Helper function for REL script objects
def Rel(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": cflags_rel,
        "progress_category": "game",
        "objects": objects,
}


def JSystemLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": [*cflags_base, "-O4,p", "-inline auto", "-RTTI on", "-enum int", "-char signed", "-sym on"],
        "progress_category": "jsystem",
        "src_dir": "src/static",
        "objects": objects,
    }


Matching = True                   # Object matches and should be linked
NonMatching = False               # Object does not match and should not be linked
Equivalent = config.non_matching  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


config.warn_missing_config = True
config.warn_missing_source = False
config.libs = [
    JSystemLib(
        "J2DGraph",
        [
            Object(Matching, "JSystem/J2DGraph/J2DGrafContext.cpp"),
            Object(Matching, "JSystem/J2DGraph/J2DOrthoGraph.cpp"),
        ],
    ),
    JSystemLib(
        "JFramework",
        [
            Object(NonMatching, "JSystem/JFramework/JFWDisplay.cpp"),
            Object(Matching, "JSystem/JFramework/JFWSystem.cpp"),
        ],
    ),
    JSystemLib(
        "JGadget",
        [
            Object(Matching, "JSystem/JGadget/linklist.cpp"),
        ],
    ),
    JSystemLib(
        "JKernel",
        [
            Object(NonMatching, "JSystem/JKernel/JKRAram.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramBlock.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramHeap.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramPiece.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRAramStream.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRArchivePri.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRArchivePub.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRCompArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDecomp.cpp"),
            Object(Matching, "JSystem/JKernel/JKRDisposer.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdAramRipper.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdFile.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRDvdRipper.cpp"),
            Object(Matching, "JSystem/JKernel/JKRExpHeap.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRFileFinder.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRFileLoader.cpp"),
            Object(Equivalent, "JSystem/JKernel/JKRHeap.cpp"), # Maybe need PCH for this?
            Object(NonMatching, "JSystem/JKernel/JKRMemArchive.cpp"),
            Object(NonMatching, "JSystem/JKernel/JKRThread.cpp"),
        ],
    ),
    JSystemLib(
        "JSupport",
        [
            
            Object(Matching, "JSystem/JSupport/JSUFileStream.cpp"),
            Object(Matching, "JSystem/JSupport/JSUInputStream.cpp"),
            Object(Matching, "JSystem/JSupport/JSUList.cpp"),
        ],
    ),
    JSystemLib(
        "JUtility",
        [
            Object(NonMatching, "JSystem/JUtility/JUTAssert.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTConsole.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTDbPrint.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTDirectFile.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTDirectPrint.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTException.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTFader.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTFont.cpp"),
            Object(Matching, "JSystem/JUtility/JUTFontData_Ascfont_fix12.s"),
            Object(NonMatching, "JSystem/JUtility/JUTGamePad.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTGraphFifo.cpp"),
            Object(Matching, "JSystem/JUtility/JUTProcBar.cpp"),
            Object(Matching, "JSystem/JUtility/JUTResFont.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTVideo.cpp"),
            Object(NonMatching, "JSystem/JUtility/JUTXfb.cpp"),
            Object(Matching, "JSystem/JUtility/JUTSDDrive.cpp"),
            Object(Matching, "JSystem/JUtility/JUTSDFile.cpp"),
            Object(Matching, "JSystem/JUtility/EXIBios.c", mw_version="GC/1.2.5n", cflags=[*cflags_base, "-O3,p", "-inline all"]),
            Object(NonMatching, "JSystem/JUtility/JUTTiff.cpp", mw_version="GC/1.3"),
        ],
    ),
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.sdk_linker_version,
        "cflags": [*cflags_runtime, "-inline auto,deferred", "-use_lmw_stmw on", "-char signed", "-fp_contract on"],
        "progress_category": "sdk",
        "src_dir": "src/static",
        "objects": [
            Object(Matching, "Runtime.PPCEABI.H/__va_arg.c"),
            Object(Matching, "Runtime.PPCEABI.H/global_destructor_chain.c"),
            Object(Matching, "Runtime.PPCEABI.H/CPlusLibPPC.cp"),
            Object(Matching, "Runtime.PPCEABI.H/NMWException.cp"),
            Object(Matching, "Runtime.PPCEABI.H/ptmf.c"),
            Object(Matching, "Runtime.PPCEABI.H/runtime.c"),
            Object(Matching, "Runtime.PPCEABI.H/__init_cpp_exceptions.cpp"),
            Object(Matching, "Runtime.PPCEABI.H/Gecko_ExceptionPPC.cp"),
            Object(Matching, "Runtime.PPCEABI.H/__mem.c"),
        ],
    },
    {
        "lib": "Famicom",
        "mw_version": "GC/1.3.2",
        "cflags": [
            *cflags_static,
            "-inline off",
            "-sdata 0",
            "-sdata2 0",
            "-sym on",
        ],
        "progress_category": "famicom",
        "src_dir": "src/static",
        "objects": [
            Object(Matching, "Famicom/ks_nes_core.cpp"),
            Object(NonMatching, "Famicom/ks_nes_draw.cpp"),
            Object(Equivalent, "Famicom/famicom.cpp"), # std::strstr appears too early in splits
            Object(Matching, "Famicom/famicom_nesinfo.cpp"),
        ],
    },
    Rel(
        "system",
        [
            Object(Matching, "system/sys_dynamic.c"),
            Object(Matching, "system/sys_math.c"),
            Object(Matching, "system/sys_math3d.c"),
            Object(Matching, "system/sys_math_atan.c"),
            Object(Matching, "system/sys_matrix.c"),
            Object(Matching, "system/sys_romcheck.c"),
            Object(Matching, "system/sys_stacks.c"),
            Object(Matching, "system/sys_ucode.c"),
            Object(Matching, "system/sys_vimgr.c"),
        ],
    ),
    Rel(
        "foresta",
        [
            Object(NonMatching, "c_keyframe.c"),
            Object(Matching, "evw_anime.c"),
            Object(NonMatching, "famicom_emu.c"),
            Object(Matching, "first_game.c"),
            Object(Matching, "game.c"),
            Object(Matching, "gamealloc.c"),
            Object(Matching, "gfxalloc.c"),
            Object(Matching, "graph.c"),
            Object(Matching, "irqmgr.c"),
            Object(Matching, "lb_rtc.c"),
            Object(Matching, "lb_reki.c"),
            Object(Matching, "player_select.c"),
            Object(Matching, "reload_data.c"),
            Object(Matching, "save_menu.c"),
            Object(Matching, "second_game.c"),
            Object(Matching, "THA_GA.c"),
            Object(Matching, "TwoHeadArena.c"),
            Object(Matching, "zurumode.c"),
        ],
    ),
    Rel(
        "effect",
        [
            Object(Matching, "effect/ef_ami_mizu.c"),
            Object(Matching, "effect/ef_anahikari.c"),
            Object(Matching, "effect/ef_ase.c"),
            Object(Matching, "effect/ef_ase2.c"),
            Object(Matching, "effect/ef_ase_ch.c"),
            Object(Matching, "effect/ef_break_axe.c"),
            Object(Matching, "effect/ef_bubu.c"),
            Object(Matching, "effect/ef_buruburu.c"),
            Object(Matching, "effect/ef_bush_happa.c"),
            Object(Matching, "effect/ef_bush_yuki.c"),
            Object(Matching, "effect/ef_car_blight.c"),
            Object(Matching, "effect/ef_car_light.c"),
            Object(Matching, "effect/ef_clacker.c"),
            Object(Matching, "effect/ef_coin.c"),
            Object(Matching, "effect/ef_dash_asimoto.c"),
            Object(Matching, "effect/ef_dig_hole.c"),
            Object(Matching, "effect/ef_dig_mud.c"),
            Object(Matching, "effect/ef_dig_scoop.c"),
            Object(Matching, "effect/ef_douzou_light.c"),
            Object(Matching, "effect/ef_doyon.c"),
            Object(Matching, "effect/ef_dust.c"),
            Object(Matching, "effect/ef_effect_control.c"),
            Object(Matching, "effect/ef_flash.c"),
            Object(Matching, "effect/ef_footprint.c"),
            Object(Matching, "effect/ef_furo_yuge.c"),
            Object(Matching, "effect/ef_gimonhu.c"),
            Object(Matching, "effect/ef_goki.c"),
            Object(Matching, "effect/ef_ha.c"),
            Object(Matching, "effect/ef_halloween.c"),
            Object(Matching, "effect/ef_halloween_smoke.c"),
            Object(Matching, "effect/ef_hanabi_botan1.c"),
            Object(Matching, "effect/ef_hanabi_botan2.c"),
            Object(Matching, "effect/ef_hanabi_dummy.c"),
            Object(Matching, "effect/ef_hanabi_hoshi.c"),
            Object(Matching, "effect/ef_hanabi_set.c"),
            Object(Matching, "effect/ef_hanabi_switch.c"),
            Object(Matching, "effect/ef_hanabi_yanagi.c"),
            Object(Matching, "effect/ef_hanabira.c"),
            Object(Matching, "effect/ef_hanatiri.c"),
            Object(Matching, "effect/ef_hirameki_den.c"),
            Object(Matching, "effect/ef_hirameki_hikari.c"),
            Object(Matching, "effect/ef_ikigire.c"),
            Object(Matching, "effect/ef_impact_star.c"),
            Object(Matching, "effect/ef_kagu_happa.c"),
            Object(Matching, "effect/ef_kamifubuki.c"),
            Object(Matching, "effect/ef_kangaeru.c"),
            Object(Matching, "effect/ef_kantanhu.c"),
            Object(Matching, "effect/ef_kasamizu.c"),
            Object(Matching, "effect/ef_kasamizutama.c"),
            Object(Matching, "effect/ef_kaze.c"),
            Object(Matching, "effect/ef_kaze_happa.c"),
            Object(Matching, "effect/ef_kigae.c"),
            Object(Matching, "effect/ef_kigae_light.c"),
            Object(Matching, "effect/ef_kikuzu.c"),
            Object(Matching, "effect/ef_killer.c"),
            Object(Matching, "effect/ef_kisha_kemuri.c"),
            Object(Matching, "effect/ef_konpu.c"),
            Object(Matching, "effect/ef_kpun.c"),
            Object(Matching, "effect/ef_kyousou_onpu.c"),
            Object(Matching, "effect/ef_lamp_light.c"),
            Object(Matching, "effect/ef_lovelove.c"),
            Object(Matching, "effect/ef_lovelove2.c"),
            Object(Matching, "effect/ef_lovelove_heart.c"),
            Object(NonMatching, "effect/ef_make_hem.c"),
            Object(Matching, "effect/ef_mizutama.c"),
            Object(Matching, "effect/ef_motiyuge.c"),
            Object(Matching, "effect/ef_muka.c"),
            Object(Matching, "effect/ef_naku.c"),
            Object(Matching, "effect/ef_namida.c"),
            Object(Matching, "effect/ef_neboke.c"),
            Object(Matching, "effect/ef_neboke_akubi.c"),
            Object(Matching, "effect/ef_neboke_awa.c"),
            Object(Matching, "effect/ef_night13_moon.c"),
            Object(Matching, "effect/ef_night15_moon.c"),
            Object(Matching, "effect/ef_nomi.c"),
            Object(Matching, "effect/ef_ongen.c"),
            Object(Matching, "effect/ef_otikomi.c"),
            Object(Matching, "effect/ef_otosiana.c"),
            Object(Matching, "effect/ef_presentopen.c"),
            Object(Matching, "effect/ef_presentopen_parts.c"),
            Object(Matching, "effect/ef_pun.c"),
            Object(Matching, "effect/ef_pun_sekimen.c"),
            Object(Matching, "effect/ef_pun_yuge.c"),
            Object(Matching, "effect/ef_resetbreak.c"),
            Object(Matching, "effect/ef_resetbreak_dust.c"),
            Object(NonMatching, "effect/ef_resetbreak_parts.c"),
            Object(Matching, "effect/ef_resetbreak_piece.c"),
            Object(Matching, "effect/ef_reset_hole.c"),
            Object(Matching, "effect/ef_room_sunshine.c"),
            Object(Matching, "effect/ef_room_sunshine_minsect.c"),
            Object(Matching, "effect/ef_room_sunshine_museum.c"),
            Object(Matching, "effect/ef_room_sunshine_police.c"),
            Object(Matching, "effect/ef_room_sunshine_posthouse.c"),
            Object(Matching, "effect/ef_sandsplash.c"),
            Object(Matching, "effect/ef_shock.c"),
            Object(Matching, "effect/ef_shooting.c"),
            Object(Matching, "effect/ef_shooting_kira.c"),
            Object(Matching, "effect/ef_shooting_set.c"),
            Object(Matching, "effect/ef_siawase_hana.c"),
            Object(Matching, "effect/ef_siawase_hana_ch.c"),
            Object(Matching, "effect/ef_siawase_hikari.c"),
            Object(Matching, "effect/ef_sibuki.c"),
            Object(Matching, "effect/ef_situren.c"),
            Object(Matching, "effect/ef_slip.c"),
            Object(Matching, "effect/ef_slip_footprint.c"),
            Object(Matching, "effect/ef_soba_yuge.c"),
            Object(Matching, "effect/ef_steam.c"),
            Object(Matching, "effect/ef_string.c"),
            Object(Matching, "effect/ef_suisou_awa.c"),
            Object(Matching, "effect/ef_swing_axe.c"),
            Object(Matching, "effect/ef_swing_net.c"),
            Object(Matching, "effect/ef_swing_rod.c"),
            Object(Matching, "effect/ef_taberu.c"),
            Object(Matching, "effect/ef_takurami.c"),
            Object(Matching, "effect/ef_takurami_kira.c"),
            Object(Matching, "effect/ef_tamaire.c"),
            Object(Matching, "effect/ef_tape.c"),
            Object(Matching, "effect/ef_tent_lamp.c"),
            Object(Matching, "effect/ef_tumble.c"),
            Object(Matching, "effect/ef_tumble_bodyprint.c"),
            Object(Matching, "effect/ef_tumble_dust.c"),
            Object(Matching, "effect/ef_turi_hamon.c"),
            Object(Matching, "effect/ef_turi_hane0.c"),
            Object(Matching, "effect/ef_turi_hane1.c"),
            Object(Matching, "effect/ef_turi_mizu.c"),
            Object(Matching, "effect/ef_turi_suiteki.c"),
            Object(Matching, "effect/ef_turn_asimoto.c"),
            Object(Matching, "effect/ef_turn_footprint.c"),
            Object(Matching, "effect/ef_uranai.c"),
            Object(Matching, "effect/ef_wait_asimoto.c"),
            Object(Matching, "effect/ef_walk_asimoto.c"),
            Object(Matching, "effect/ef_warau.c"),
            Object(Matching, "effect/ef_yajirushi.c"),
            Object(Matching, "effect/ef_young_tree.c"),
            Object(Matching, "effect/ef_yukidama.c"),
            Object(Matching, "effect/ef_yukidaruma.c"),
            Object(Matching, "effect/ef_yukihane.c"),
        ],
    ),
    Rel(
        "game",
        [
            Object(NonMatching, "game/m_play.c"),
            Object(Matching, "game/m_prenmi.c"),
            Object(NonMatching, "game/m_select.c"),
            Object(Matching, "game/m_trademark.c"),
            Object(Matching, "game/m_train_control.c"),
            Object(Matching, "game/m_vibctl.c"),
            Object(Matching, "game/m_view.c"),
            Object(Matching, "game/m_watch_my_step.c"),
        ],
    ),
]


# Define our custom asset processing scripts
config.custom_build_rules = [
    {
        "name": "convert_pal16",
        "command": "$python tools/converters/pal16dis.py $in $out",
        "description": "CONVERT $symbol",
    },
    # We run the script in "scan" mode first to generate a .dd (dyndep) file
    # This allows ninja to understand what files are generated by the script
    {
        "name": "scan_pal16_chunked",
        "command": "$python tools/converters/pal16dis_chunked.py $in $base -s $stamp -d $out",
        "description": "SCAN $symbol",
    },
    {
        "name": "convert_pal16_chunked",
        "command": "$python tools/converters/pal16dis_chunked.py $in $base -s $out",
        "description": "CONVERT $symbol",
    },
    {
        "name": "convert_vtx",
        "command": "$python tools/converters/vtxdis.py $in $out",
        "description": "CONVERT $symbol",
    },
]
config.custom_build_steps = {}

# Grab the specific GameID so we can format our strings properly
version = VERSIONS[version_num]
out_dir = config.build_dir / version


# This generates the build steps needed for preprocessing
def emit_build_rule(asset):
    steps = config.custom_build_steps.setdefault("pre-compile", [])

    match asset.get("custom_type"):
        case None:
            return

        case "pal16":
            steps.append(
                {
                    "rule": "convert_pal16",
                    "inputs": out_dir / "bin" / asset["binary"],
                    "outputs": out_dir / "include" / asset["header"],
                    "variables": {
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/pal16dis.py"),
                }
            )

        case "pal16c":
            # Run the script in scan mode first to generate a .dd file
            input = out_dir / "bin" / asset["binary"]
            out_base = out_dir / "include" / asset["header"]
            dyndep = out_dir / "include" / f"{asset['header']}.dd"
            # We need a stamp file to use as a marker for ninja
            stamp = out_dir / "include" / f"{asset['header']}.stamp"
            steps.append(
                {
                    "rule": "scan_pal16_chunked",
                    "inputs": input,
                    "outputs": dyndep,
                    "variables": {
                        "base": out_base,
                        "stamp": stamp,
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/pal16dis_chunked.py"),
                }
            )
            # Now the script will generate all the dynamic outputs and stamp file
            steps.append(
                {
                    "rule": "convert_pal16_chunked",
                    "inputs": input,
                    "outputs": stamp,
                    "variables": {
                        "base": out_base,
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/pal16dis_chunked.py"),
                    "dyndep": dyndep,
                    "order_only": dyndep,
                }
            )

        case "vtx":
            steps.append(
                {
                    "rule": "convert_vtx",
                    "inputs": out_dir / "bin" / asset["binary"],
                    "outputs": out_dir / "include" / asset["header"],
                    "variables": {
                        "symbol": asset["symbol"],
                    },
                    "implicit": Path("tools/converters/vtxdis.py"),
                }
            )

        case _:
            print("Unknown asset type: " + asset["custom_type"])


# Parse the config and create the build rules for all our assets
config_path = out_dir / "config.json"
if config_path.exists():
    config_data = json.load(open(config_path))
    for asset in config_data.get("extract", []):
        emit_build_rule(asset)
    for module in config_data.get("modules", []):
        for asset in module.get("extract", []):
            emit_build_rule(asset)


## Fetch N64 SDK files
N64_SDK_files = [
    "include/PR/abi.h",
    "include/PR/gbi.h",
    "include/PR/gs2dex.h",
    "include/PR/mbi.h",
    "include/PR/ultratypes.h",
    "include/compiler/gcc/stdlib.h",
]

OWNER = "decompals"
REPO = "ultralib"
BRANCH = "main"


def fetch_file_raw(path):
    url = f"https://raw.githubusercontent.com/{OWNER}/{REPO}/{BRANCH}/{path}"
    req = urllib.request.Request(url)
    req.add_header("User-Agent", "Mozilla/5.0")
    return urllib.request.urlopen(req)


for file_path in N64_SDK_files:
    local_path = os.path.join("include", file_path.split("include/")[-1])
    os.makedirs(os.path.dirname(local_path), exist_ok=True)

    if not os.path.exists(local_path):
        print(f"Fetching {file_path}...")

        try:
            response = fetch_file_raw(file_path)
            content = response.read()

            # Special case: patch gbi.h
            if os.path.normpath(local_path) == os.path.normpath("include/PR/gbi.h"):
                content = re.sub(
                    rb"unsigned char\s+param:8;", b"unsigned int\tparam:8;", content
                )

            with open(local_path, "wb") as f:
                f.write(content)

        except urllib.error.HTTPError as e:
            print(f"Failed to fetch {file_path}: HTTP {e.code} {e.reason}")
        except Exception as e:
            print(f"Error fetching {file_path}: {e}")


# Optional callback to adjust link order. This can be used to add, remove, or reorder objects.
# This is called once per module, with the module ID and the current link order.
#
# For example, this adds "dummy.c" to the end of the DOL link order if configured with --non-matching.
# "dummy.c" *must* be configured as a Matching (or Equivalent) object in order to be linked.
def link_order_callback(module_id: int, objects: List[str]) -> List[str]:
    # Don't modify the link order for matching builds
    if not config.non_matching:
        return objects
    if module_id == 0:  # DOL
        return objects + ["dummy.c"]
    return objects


# Uncomment to enable the link order callback.
# config.link_order_callback = link_order_callback


# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    ProgressCategory("game", "Game Code"),
    ProgressCategory("sdk", "SDK Code"),
    ProgressCategory("jsystem", "JSystem"),
    ProgressCategory("famicom", "NES Emulator"),
]
config.progress_each_module = args.verbose
# Optional extra arguments to `objdiff-cli report generate`
config.progress_report_args = [
    # Marks relocations as mismatching if the target value is different
    # Default is "functionRelocDiffs=none", which is most lenient
    # "--config functionRelocDiffs=data_value",
]

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress information
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
