#include "ac_shop_design.h"

#include "m_actor_type.h"
#include "m_common_data.h"
#include "m_name_table.h"
#include "m_room_type.h"
#include "m_shop.h"

#define ITEM_IS_RSV_SHOP(item) ((item) >= RSV_SHOP_PAPER && (item) <= RSV_SHOP_MEDICINE)
#define ITEM_IS_RSV_SHOP_SOLDOUT(item) (((item) >= RSV_SHOP_SOLDOUT && (item) <= RSV_SHOP_SOLD_MEDICINE))

enum {
    aSD_LAYOUT_TYPE_NOMRAL,
    aSD_LAYOUT_TYPE_SPECIAL,
    aSD_LAYOUT_TYPE_HUKUBUKURO,

    aSD_LAYOUT_TYPE_NUM,
};

enum {
    aSD_LAYOUT_IDX_SHOP0,
    aSD_LAYOUT_IDX_CONVENI,
    aSD_LAYOUT_IDX_SUPER,
    aSD_LAYOUT_IDX_DEPART,
    aSD_LAYOUT_IDX_DEPART_2,

    aSD_LAYOUT_IDX_NUM,
};

static void Shop_Design_Actor_ct(ACTOR* actorx, GAME* game);
static void Shop_Design_Actor_dt(ACTOR* actorx, GAME* game);
static void Shop_Design_Actor_move(ACTOR* actorx, GAME* game);
static void Shop_Design_Actor_draw(ACTOR* actorx, GAME* game);

ACTOR_PROFILE Shop_Design_Profile = {
    mAc_PROFILE_SHOP_DESIGN,
    ACTOR_PART_CONTROL,
    ACTOR_STATE_NO_DRAW_WHILE_CULLED | ACTOR_STATE_NO_MOVE_WHILE_CULLED,
    EMPTY_NO,
    ACTOR_OBJ_BANK_KEEP,
    sizeof(SHOP_DESIGN_ACTOR),
    &Shop_Design_Actor_ct,
    &Shop_Design_Actor_dt,
    &Shop_Design_Actor_move,
    &Shop_Design_Actor_draw,
    NULL,
};

static mActor_name_t aSD_ItemName2ReservePointName(mActor_name_t item) {
    int tanuki_shop_status = Common_Get(tanuki_shop_status);

    if (item == ITM_HUKUBUKURO_BAG) {
        return RSV_SHOP_HALLOWEEN;
    }

    if (item == ITM_CRACKER) {
        return RSV_SHOP_HALLOWEEN;
    }

    if (item >= ITM_YELLOW_PINWHEEL && item <= ITM_FANCY_PINWHEEL) {
        return RSV_SHOP_PAINT;
    }

    if (item >= ITM_BLUEBELL_FAN && item <= ITM_LEAF_FAN) {
        return RSV_SHOP_TOOL;
    }

    if (mNT_ftr_item_no_to_ftr_idx(item) >= FTR_NOG_BALLOON_COMMON0 && mNT_ftr_item_no_to_ftr_idx(item) <= FTR_NOG_BALLOON_COMMON7) {
        return RSV_SHOP_PLANT;
    }

    if (item == ITM_MEDICINE) {
        return RSV_SHOP_MEDICINE;
    }

    if (item == RSV_SHOP_SOLD_MEDICINE) {
        return RSV_SHOP_MEDICINE;
    }

    if (item == ITM_SIGNBOARD) {
        return RSV_SHOP_SIGNBOARD;
    }

    if (item == RSV_SHOP_SOLD_SIGNBOARD) {
        return RSV_SHOP_SIGNBOARD;
    }

    if (ITEM_IS_FTR(item)) {
        return RSV_SHOP_FTR;
    }

    if (item == RSV_SHOP_SOLD_FTR) {
        return RSV_SHOP_FTR;
    }

    if ((item >= ITM_PAPER_START && item <= ITM_PAPER_END) || (item >= ITM_DIARY00 && item <= ITM_DIARY15)) {
        return RSV_SHOP_PAPER;
    }

    if (item == RSV_SHOP_SOLD_PAPER) {
        return RSV_SHOP_PAPER;
    }

    if (item >= ITM_CARPET_START && item <= (ITM_CARPET_END - 4)) {
        return RSV_SHOP_CARPET;
    }

    if (item == RSV_SHOP_SOLD_CARPET) {
        return RSV_SHOP_CARPET;
    }

    if (item >= ITM_WALL_START && item <= (ITM_WALL_END - 4)) {
        return RSV_SHOP_WALL;
    }

    if (item == RSV_SHOP_SOLD_WALL) {
        return RSV_SHOP_WALL;
    }

    if ((item >= ITM_CLOTH_START && item <= ITM_CLOTH_END)) {
        return RSV_SHOP_CLOTH;
    }

    if (item == RSV_SHOP_SOLD_CLOTH) {
        return RSV_SHOP_CLOTH;
    }

    if ((item >= ITM_TOOL_START && item <= ITM_TOOL_END)) {
        if (item >= ITM_UMBRELLA_START && item <= (ITM_UMBRELLA_END - 1)) {
            return RSV_SHOP_UMBRELLA;
        }

        if (item >= ITM_RED_PAINT && item <= ITM_BROWN_PAINT) {
            return RSV_SHOP_PAINT;
        }

        /* @BUG - this is impossible to reach, maybe signboard used to be in the TOOL category before? */
        if (item == ITM_SIGNBOARD) {
            return RSV_SHOP_SIGNBOARD;
        }

        return RSV_SHOP_TOOL;
    }

    if (item == RSV_SHOP_SOLD_TOOL) {
        return RSV_SHOP_TOOL;
    }

    if (item == RSV_SHOP_SOLD_UMBRELLA) {
        return RSV_SHOP_UMBRELLA;
    }

    if (item == RSV_SHOP_SOLD_PAINT) {
        return RSV_SHOP_PAINT;
    }

    if ((item >= ITM_SAPLING && item <= ITM_CEDAR_SAPLING) ||
        ((ITEM_IS_FLOWER_BAG(item) &&
          (tanuki_shop_status == mSP_TANUKI_SHOP_STATUS_HALLOWEEN || tanuki_shop_status == mSP_TANUKI_SHOP_STATUS_CRACKER)))) {
        return RSV_SHOP_PLANT;
    }

    if (ITEM_IS_FLOWER_BAG(item) || (item == ITM_FOOD_CANDY && tanuki_shop_status == mSP_TANUKI_SHOP_STATUS_HALLOWEEN)) {
        return RSV_SHOP_HALLOWEEN;
    }

    if (item == RSV_SHOP_SOLD_PLANT) {
        return RSV_SHOP_PLANT;
    }

    if (item == RSV_SHOP_SOLD_FE16) {
        return RSV_SHOP_HALLOWEEN;
    }

    return EMPTY_NO;
}

static void aSD_MakeGoodsFg(mActor_name_t* goods_p, int count) {
    int i;

    for (i = 0; i < count; i++) {
        if (goods_p[i] != EMPTY_NO) {
            mActor_name_t reserve_name = aSD_ItemName2ReservePointName(goods_p[i]);

            if (reserve_name != EMPTY_NO) {
                mSP_SetGoods2ReservedPoint(goods_p[i], reserve_name);
            }
        }
    }
}

/* Mispelling of 'rare' */
static void aSD_MakeReaGoodsFg(mActor_name_t item) {
    if (item != EMPTY_NO) {
        mSP_SetGoods2ReservedPoint(item, RSV_SHOP_RARE);
    }
}

static void aSD_MakeLotteryGoodsFg(mActor_name_t* lottery_items) {
    mSP_SetGoods2ReservedPoint(lottery_items[2], RSV_SHOP_FTR);
    mSP_SetGoods2ReservedPoint(lottery_items[0], RSV_SHOP_FTR);
    mSP_SetGoods2ReservedPoint(lottery_items[1], RSV_SHOP_FTR);
}

static mActor_name_t aSD_UnitNum2ItemNo(int ux, int uz);
static int aSD_ReportGoodsSales(int ux, int uz);

static void aSD_SetClipProc(ACTOR* actorx, int clear) {
    SHOP_DESIGN_ACTOR* shop_design = (SHOP_DESIGN_ACTOR*)actorx;

    if (clear) {
        Common_Get(clip).shop_design_clip = NULL;
    } else {
        Common_Get(clip).shop_design_clip = &shop_design->clip;
        shop_design->clip.design_actor = shop_design;
        shop_design->clip.unitNum2ItemNo_proc = &aSD_UnitNum2ItemNo;
        shop_design->clip.reportGoodsSale_proc = &aSD_ReportGoodsSales;
    }
}

static int aSD_CountElementInGoodsList(void) {
    mActor_name_t* items = Save_Get(shop).items;
    int count = 0;
    int i;
    
    for (i = 0; i < mSP_GOODS_COUNT; i++) {
        if (items[i] != EMPTY_NO) {
            count++;
        }
    }

    return count;
}

static void aSD_GetGoodsInfo(SHOP_DESIGN_ACTOR* shop_design) {
    if (Common_Get(tanuki_shop_status) == mSP_TANUKI_SHOP_STATUS_EVENT) {
        int count = 0;
        int i;

        shop_design->goods_list = Save_Get(shop).event_goods;
        shop_design->goods_list_max = mSP_GOODS_COUNT;
        for (i = 0; i < shop_design->goods_list_max; i++) {
            if (shop_design->goods_list[i] != EMPTY_NO) {
                count++;
            }
        }
        shop_design->goods_list_count = count;
    } else {
        shop_design->goods_list = Save_Get(shop).items;
        shop_design->goods_list_count = aSD_CountElementInGoodsList();
        shop_design->goods_list_max = mSP_GOODS_COUNT;
    }

    /* Check if player is from a different town and, if so, set the flag for Nookington's */
    mSP_SetNewVisitor();
}

static void aSD_SetReservedPointFill000(void) {
    mActor_name_t* fg_p = mFI_BkNumtoUtFGTop(0, 0);
    int i;

    for (i = 0; i < UT_TOTAL_NUM; i++) {
        if (ITEM_IS_RSV_SHOP(fg_p[i])) {
            fg_p[i] = RSV_NO; // TODO: I suppose RSV_NO is actually called 'FILL000'
        }
    }
}

static int aSD_SceneNoToArgData(int scene_no) {
    switch (scene_no) {
        case SCENE_SHOP0:
            return 0;
        case SCENE_CONVENI:
            return 1;
        case SCENE_SUPER:
            return 2;
        case SCENE_DEPART:
            return 3;
        default:
            return -1;
    }
}

static void aSD_SetGaragara(ACTOR* actorx, GAME* game) {
    GAME_PLAY* play = (GAME_PLAY*)game;

    /* Check if the shop is currently having the monthly lottery raffle */
    if (!mSP_force_opend() && Common_Get(tanuki_shop_status) == mSP_TANUKI_SHOP_STATUS_FUKUBIKI && actorx->actor_specific != -1) {
        /* garagara likely referes to ガラガラ抽選 or 'raffle drum/rattle lottery' */
        static xyz_t garagara_set_table[] = {
            { 160.0f, 60.0f, 190.0f }, /* Nook's Cranny */
            { 240.0f, 60.0f, 190.0f }, /* Nook 'n' Go */
            { 240.0f, 60.0f, 350.0f }, /* Nookway */
            { 240.0f, 60.0f, 350.0f }, /* Nookington's */
            { 160.0f, 60.0f, 180.0f }, /* Nookington's 2nd floor? */
        };

        /* Make the raffle drum actor */
        Actor_info_make_actor(&play->actor_info, game, mAc_PROFILE_GARAGARA,
                              garagara_set_table[actorx->actor_specific].x,
                              garagara_set_table[actorx->actor_specific].y,
                              garagara_set_table[actorx->actor_specific].z, 0, 0, 0, -1, -1, -1, EMPTY_NO, 0, -1, -1);
    }
}

// clang-format off
static mActor_name_t aSD_shop_normal_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_WALL, RSV_SHOP_CARPET, RSV_SHOP_TOOL, RSV_SHOP_TOOL,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CLOTH, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_PAPER, RSV_SHOP_MEDICINE, RSV_SHOP_HALLOWEEN, RSV_SHOP_PLANT,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_shop_special_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_WALL, RSV_SHOP_CARPET, RSV_SHOP_TOOL, RSV_SHOP_PAINT,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CLOTH, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_PLANT,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_conveni_normal_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_PLANT, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_MEDICINE, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_CARPET, RSV_SHOP_WALL, RSV_SHOP_PAPER, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_TOOL, RSV_SHOP_TOOL, RSV_SHOP_TOOL, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_conveni_special_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_CARPET, RSV_SHOP_WALL, RSV_SHOP_TOOL, RSV_SHOP_TOOL, EMPTY_NO, EMPTY_NO,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_PAINT, RSV_SHOP_PAINT, RSV_SHOP_PLANT, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_super_normal_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_RARE, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_FTR,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PLANT, EMPTY_NO, RSV_SHOP_WALL, EMPTY_NO, RSV_SHOP_WALL, EMPTY_NO, RSV_SHOP_CLOTH,RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PLANT, EMPTY_NO, RSV_SHOP_CARPET, EMPTY_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_TOOL, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_TOOL, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO,   RSV_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_SIGNBOARD, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO,   RSV_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_MEDICINE, EMPTY_NO, RSV_SHOP_PAINT, EMPTY_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_super_special_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_FTR,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, RSV_SHOP_WALL, EMPTY_NO, RSV_SHOP_WALL, EMPTY_NO, RSV_SHOP_CLOTH,RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, RSV_SHOP_CARPET, EMPTY_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_PLANT, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_PLANT, EMPTY_NO,   RSV_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_PLANT, EMPTY_NO,   RSV_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_depart1_normal_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO, RSV_SHOP_TOOL, RSV_SHOP_TOOL, RSV_SHOP_TOOL, RSV_SHOP_SIGNBOARD, RSV_SHOP_PAINT, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PLANT, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PLANT, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PLANT, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_PAPER, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_MEDICINE, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_depart1_special_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO, RSV_SHOP_PLANT, RSV_SHOP_PLANT, RSV_SHOP_PLANT, RSV_SHOP_PLANT, RSV_SHOP_PLANT, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_PAINT, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_TOOL, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_depart2_normal_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CARPET, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_WALL, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_WALL, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_RARE, EMPTY_NO, EMPTY_NO,RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_WALL, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_depart2_special_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CARPET, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_WALL, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_WALL, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_WALL, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,RSV_SHOP_FTR, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_shop_hukubukuro_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_WALL, RSV_SHOP_CARPET, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_CLOTH, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_conveni_hukubukuro_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_CLOTH, RSV_SHOP_CLOTH,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_CARPET, RSV_SHOP_WALL, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_super_hukubukuro_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_RARE, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO, RSV_SHOP_FTR,EMPTY_NO, RSV_SHOP_FTR, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_WALL, EMPTY_NO, RSV_SHOP_WALL, EMPTY_NO, RSV_SHOP_CLOTH,RSV_SHOP_CLOTH, RSV_SHOP_CLOTH, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_CARPET, EMPTY_NO, RSV_SHOP_CARPET, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO,   RSV_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO,   RSV_NO,EMPTY_NO,   RSV_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,  RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};

static mActor_name_t aSD_depart1_hukubukuro_layout[UT_TOTAL_NUM] = {
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, RSV_SHOP_HALLOWEEN, EMPTY_NO, EMPTY_NO, EMPTY_NO, RSV_SHOP_UMBRELLA, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
      RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO,   RSV_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
    EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO, EMPTY_NO,
};
// clang-format on

static void aSD_CleanReserve(void) {
    mActor_name_t* fg_p = mFI_BkNumtoUtFGTop(0, 0);
    int i;

    for (i = 0; i < UT_TOTAL_NUM; i++) {
        if (ITEM_IS_RSV_SHOP(fg_p[i])) {
            fg_p[i] = EMPTY_NO;
        }
    }
}

static void aSD_SetReserveFG(mActor_name_t* reserve_list_p) {
    mActor_name_t* fg_p = mFI_BkNumtoUtFGTop(0, 0);
    int i;

    for (i = 0; i < UT_TOTAL_NUM; i++) {
        if (ITEM_IS_RSV_SHOP(reserve_list_p[i])) {
            fg_p[i] = reserve_list_p[i];
        }
    }
}

static void aSD_ChangeSpecialLayout(int scene_no) {
    int status = Common_Get(tanuki_shop_status);
    int layout_idx = -1;
    int layout_type;

    switch (scene_no) {
        case SCENE_SHOP0:
            layout_idx = aSD_LAYOUT_IDX_SHOP0;
            break;
        case SCENE_CONVENI:
            layout_idx = aSD_LAYOUT_IDX_CONVENI;
            break;
        case SCENE_SUPER:
            layout_idx = aSD_LAYOUT_IDX_SUPER;
            break;
        case SCENE_DEPART:
            layout_idx = aSD_LAYOUT_IDX_DEPART;
            break;
        case SCENE_DEPART_2:
            layout_idx = aSD_LAYOUT_IDX_DEPART_2;
            break;
    }

    switch (status) {
        case mSP_TANUKI_SHOP_STATUS_EVENT:
            layout_type = aSD_LAYOUT_TYPE_SPECIAL;
            break;
        case mSP_TANUKI_SHOP_STATUS_FUKUBIKI:
            if (mSP_force_opend()) {
                layout_type = aSD_LAYOUT_TYPE_NOMRAL;
            } else {
                layout_type = -1;
            }
            break;
        case mSP_TANUKI_SHOP_STATUS_HUKUBUKURO_SALE:
            layout_type = aSD_LAYOUT_TYPE_HUKUBUKURO;
            break;
        default:
            layout_type = aSD_LAYOUT_TYPE_NOMRAL;
            break;
    }

    if (layout_idx != -1 && layout_type != -1) {
        static mActor_name_t* aSD_special_layout_table[aSD_LAYOUT_IDX_NUM] = {
            aSD_shop_special_layout, // aSD_LAYOUT_IDX_SHOP0
            aSD_conveni_special_layout, // aSD_LAYOUT_IDX_CONVENI
            aSD_super_special_layout, // aSD_LAYOUT_IDX_SUPER
            aSD_depart1_special_layout, // aSD_LAYOUT_IDX_DEPART
            aSD_depart2_special_layout, // aSD_LAYOUT_IDX_DEPART_2
        };
        
        static mActor_name_t* aSD_hukubukuro_layout_table[aSD_LAYOUT_IDX_NUM] = {
            aSD_shop_hukubukuro_layout, // aSD_LAYOUT_IDX_SHOP0
            aSD_conveni_hukubukuro_layout, // aSD_LAYOUT_IDX_CONVENI
            aSD_super_hukubukuro_layout, // aSD_LAYOUT_IDX_SUPER
            aSD_depart1_hukubukuro_layout, // aSD_LAYOUT_IDX_DEPART
            aSD_depart2_normal_layout, // aSD_LAYOUT_IDX_DEPART_2
        };
        
        static mActor_name_t* aSD_normal_layout_table[aSD_LAYOUT_IDX_NUM] = {
            aSD_shop_normal_layout, // aSD_LAYOUT_IDX_SHOP0
            aSD_conveni_normal_layout, // aSD_LAYOUT_IDX_CONVENI
            aSD_super_normal_layout, // aSD_LAYOUT_IDX_SUPER
            aSD_depart1_normal_layout, // aSD_LAYOUT_IDX_DEPART
            aSD_depart2_normal_layout, // aSD_LAYOUT_IDX_DEPART_2
        };
        
        static mActor_name_t** aSD_shop_layput_table[aSD_LAYOUT_TYPE_NUM] = {
            aSD_normal_layout_table, // aSD_LAYOUT_TYPE_NOMRAL
            aSD_special_layout_table, // aSD_LAYOUT_TYPE_SPECIAL
            aSD_hukubukuro_layout_table, // aSD_LAYOUT_TYPE_HUKUBUKURO
        };
        
        mActor_name_t** layout_table = aSD_shop_layput_table[layout_type];

        if (layout_table[layout_idx] != NULL) {
            aSD_CleanReserve();
            aSD_SetReserveFG(layout_table[layout_idx]);
        }
    }
}

static void Shop_Design_Actor_ct(ACTOR* actorx, GAME* game) {
    SHOP_DESIGN_ACTOR* shop_design = (SHOP_DESIGN_ACTOR*)actorx;
    GAME_PLAY* play = (GAME_PLAY*)game;
    int scene_no = Save_Get(scene_no);

    actorx->actor_specific = aSD_SceneNoToArgData(scene_no);
    aSD_SetGaragara(actorx, game);
    aSD_ChangeSpecialLayout(scene_no);

    if (mFI_CheckShop()) {
        aSD_GetGoodsInfo(shop_design);
        if (Common_Get(tanuki_shop_status) == mSP_TANUKI_SHOP_STATUS_FUKUBIKI) {
            if (!mSP_force_opend()) {
                aSD_MakeLotteryGoodsFg(Save_Get(shop).lottery_items);
            }
        } else {
            aSD_MakeGoodsFg(shop_design->goods_list, shop_design->goods_list_count);
            if (Common_Get(tanuki_shop_status) != mSP_TANUKI_SHOP_STATUS_EVENT) {
                aSD_MakeReaGoodsFg(Save_Get(shop).rare_item);
            }

        }

        aSD_SetReservedPointFill000();
        aSD_SetClipProc(actorx, FALSE);
    }
}

static void Shop_Design_Actor_dt(ACTOR* actorx, GAME* game) {
    aSD_SetClipProc(actorx, TRUE);
}

static void Shop_Design_Actor_draw(ACTOR* actorx, GAME* game) {
    // nothing
}

static void Shop_Design_Actor_move(ACTOR* actorx, GAME* game) {
    // nothing
}

static mActor_name_t aSD_UnitNum2ItemNo(int ux, int uz) {
    int bx = ux / UT_X_NUM;
    int bz = uz / UT_Z_NUM;
    mActor_name_t* fg_p = mFI_BkNumtoUtFGTop(bx, bz);
    int local_ux = ux - bx * UT_X_NUM;
    int local_uz = uz - bz * UT_Z_NUM;
    mActor_name_t item = fg_p[local_ux + local_uz * UT_X_NUM];

    if (ITEM_IS_RSV_SHOP_SOLDOUT(item)) {
        return RSV_NO;
    }

    if (
        // clang-format off
        ITEM_IS_FTR(item) ||
        (item >= ITM_PAPER_START && item <= ITM_PAPER_END) ||
        (item >= ITM_CARPET_START && item <= ITM_CARPET_END - 4) ||
        (item >= ITM_WALL_START && item <= ITM_WALL_END - 4) ||
        (item >= ITM_CLOTH_START && item <= ITM_CLOTH_END) ||
        (item >= ITM_TOOL_START && item <= ITM_TOOL_END) ||
        (item >= ITM_SAPLING && item <= ITM_CEDAR_SAPLING) ||
        ITEM_IS_FLOWER_BAG(item) ||
        (item >= ITM_DIARY00 && item <= ITM_DIARY15) ||
        (item == ITM_FOOD_CANDY) ||
        (item == RSV_FE1F) ||
        (item == ITM_HUKUBUKURO_BAG) ||
        (item == ITM_SIGNBOARD) ||
        (item == ITM_MEDICINE)
        // clang-format on
    ) {
        if (item == RSV_FE1F) {
            if (aMR_CLIP != NULL) {
                mActor_name_t ftr_item;

                aMR_CLIP->unitNum2ftrItemNoftrId_proc(&ftr_item, NULL, ux, uz, mCoBG_LAYER0);
                return ftr_item;
            } else {
                return RSV_NO;
            }
        } else {
            return item;
        }
    } else {
        return RSV_NO;
    }
}

static int aSD_ReportGoodsSales(int ux, int uz) {
    mActor_name_t item = aSD_UnitNum2ItemNo(ux, uz);
    u32 price = mSP_ItemNo2ItemPrice_Tanu(item);
    mActor_name_t rsv_item = EMPTY_NO;
    mActor_name_t event_rsv_item = EMPTY_NO;
    mActor_name_t ftr_item;
    int tanuki_shop_status = Common_Get(tanuki_shop_status);
    int ftrID;

    if (CLIP(shop_design_clip) != NULL) {
        SHOP_DESIGN_ACTOR* shop_design = CLIP(shop_design_clip)->design_actor;

        mSP_PlusSales(price);
        
        if (item == ITM_HUKUBUKURO_BAG || item == ITM_CRACKER) {
            event_rsv_item = RSV_SHOP_SOLD_FE16;
        }
        
        if (item >= ITM_YELLOW_PINWHEEL && item <= ITM_FANCY_PINWHEEL) {
            event_rsv_item = RSV_SHOP_SOLD_PAINT;
        }
        
        if (item >= ITM_BLUEBELL_FAN && item <= ITM_LEAF_FAN) {
            event_rsv_item = RSV_SHOP_SOLD_TOOL;
        }

        if (event_rsv_item != EMPTY_NO) {
            mSP_ShopSaleReport(item, shop_design->goods_list, shop_design->goods_list_max, event_rsv_item);
            mFI_UtNumtoFGSet_common(event_rsv_item, ux, uz, FALSE);
            return FALSE;
        }

        if (item >= ITM_SAPLING && item <= ITM_CEDAR_SAPLING) {
            rsv_item = RSV_SHOP_SOLD_PLANT;
        }

        if (ITEM_IS_FLOWER_BAG(item)) {
            if (tanuki_shop_status == mSP_TANUKI_SHOP_STATUS_HALLOWEEN || tanuki_shop_status == mSP_TANUKI_SHOP_STATUS_CRACKER) {
                rsv_item = RSV_SHOP_SOLD_PLANT;
            } else {
                rsv_item = RSV_SHOP_SOLD_FE16;
            }
        }

        if (item == ITM_FOOD_CANDY) {
            rsv_item = RSV_SHOP_SOLD_FE16;
        }

        if (item >= ITM_CLOTH_START && item <= ITM_CLOTH_END) {
            mSP_ShopSaleReport(item, shop_design->goods_list, shop_design->goods_list_max, RSV_SHOP_SOLD_CLOTH);
            CLIP(shop_manekin_clip)->change2naked_manekin_proc(ux, uz);
            mFI_UtNumtoFGSet_common(RSV_NO, ux, uz, FALSE);
            return FALSE;
        }

        if (ITEM_IS_FTR(item) && aMR_CLIP != NULL) {
            aMR_CLIP->unitNum2ftrItemNoftrId_proc(&ftr_item, &ftrID, ux, uz, mCoBG_LAYER0);
            aMR_CLIP->ftrId2extinguishFtr_proc(ftrID);

            if (mNT_ftr_item_no_to_ftr_idx(item) >= FTR_NOG_BALLOON_COMMON0 && mNT_ftr_item_no_to_ftr_idx(item) <= FTR_NOG_BALLOON_COMMON7) {
                rsv_item = RSV_SHOP_SOLD_PLANT;
            } else if (item == Save_Get(shop).rare_item && tanuki_shop_status != mSP_TANUKI_SHOP_STATUS_EVENT) {
                rsv_item = RSV_SHOP_SOLD_RARE;
            } else {
                rsv_item = RSV_SHOP_SOLD_FTR;
            }
        }

        if (ITEM_IS_REG_CARPET(item)) {
            rsv_item = RSV_SHOP_SOLD_CARPET;
        }

        if (ITEM_IS_REG_WALL(item)) {
            rsv_item = RSV_SHOP_SOLD_WALL;
        }

        if (item == ITM_SIGNBOARD) {
            rsv_item = RSV_SHOP_SOLD_SIGNBOARD;
        }

        if (item == ITM_MEDICINE) {
            rsv_item = RSV_SHOP_SOLD_MEDICINE;
        } else if (item >= ITM_TOOL_START && item <= ITM_TOOL_END) {
            if (ITEM_IS_UMBRELLA2(item)) {
                if (CLIP(shop_umbrella_clip) != NULL) {
                    CLIP(shop_umbrella_clip)->delete_umbrella_proc(ux, uz);
                }

                rsv_item = RSV_SHOP_SOLD_UMBRELLA;
            } else if (ITEM_IS_PAINT(item)) {
                rsv_item = RSV_SHOP_SOLD_PAINT;
            } else if (item == ITM_SIGNBOARD) {
                rsv_item = RSV_SHOP_SOLD_SIGNBOARD;
            } else {
                rsv_item = RSV_SHOP_SOLD_TOOL;
            }
        }

        if (item >= ITM_PAPER_START && item <= ITM_PAPER_END) {
            return TRUE;
        }

        if (item >= ITM_DIARY00 && item <= ITM_DIARY15) {
            rsv_item = RSV_SHOP_SOLD_PAPER;
        }

        if (tanuki_shop_status == mSP_TANUKI_SHOP_STATUS_EVENT && !mEv_CheckEvent(mEv_SPNPC_SHOP)) {
            return FALSE;
        }

        if (rsv_item != EMPTY_NO) {
            if (mSP_ShopSaleReport(item, shop_design->goods_list, shop_design->goods_list_max, rsv_item)) {
                return TRUE;
            }

            mFI_UtNumtoFGSet_common(rsv_item, ux, uz, FALSE);
        }
        
        return FALSE;
    }

    return FALSE;
}
