#ifndef AC_STATION_CLIP_H
#define AC_STATION_CLIP_H

#include "types.h"
#include "m_actor.h"

#ifdef __cplusplus
extern "C" {
#endif

#define aSTM_LIVE_MUSIC_INDEX (ITM_MINIDISK_LIVE68 - ITM_MINIDISK_LIVE58)

enum {
    aSTC_SD_SELECT_BUSY = -1,
    aSTC_SD_SELECT_ERROR,
    aSTC_SD_SELECT_TOWN,
    aSTC_SD_SELECT_END,
    aSTC_SD_SELECT_WRITE_PROTECTED
};

enum {
    aSTC_SD_CHECK_BUSY,
    aSTC_SD_CHECK_CARD,
    aSTC_SD_CHECK_SINGLE_TOWN,
    aSTC_SD_CHECK_MULTIPLE_TOWNS,
    aSTC_SD_CHECK_WRITE_PROTECTED,
    aSTC_SD_CHECK_ERROR
};

enum {
    aSTM_TALK_CHK_LEAVE_TALK,
    aSTM_TALK_CHK_LEAVE_TALK2,
    aSTM_TALK_SAYONARA,
    aSTM_TALK_CHK_TRAIN_TALK,
    aSTM_TALK_CHK_TRAIN2_TALK,
    aSTM_TALK_BEFORE_SAVE_TALK,
    aSTM_TALK_SAVE_TALK,
    aSTM_TALK_CHK_OVER_SAVE_TALK,
    aSTM_TALK_SAVE_TALK_END,
    aSTM_TALK_SAVE_ERROR,
    aSTM_TALK_CHK_REPAIRID,
    aSTM_TALK_REPAIRID_BF,
    aSTM_TALK_REPAIRID,
    aSTM_TALK_REPAIRID_AFTER,
    aSTM_TALK_CARDPROC,
    aSTM_TALK_SDCARDPROC,
    aSTM_TALK_SDCARD_WHITCH,
    aSTM_TALK_SDCARD_SELECT_0,
    aSTM_TALK_SDCARD_SELECT_1,
    aSTM_TALK_SDCARD_SELECT_2,
    aSTM_TALK_GIVE_LIVE_MD,
    aSTM_TALK_END_WAIT,

    aSTM_TALK_NUM
};

typedef int (*aSTC_CHANGE_TALK_PROC)(ACTOR*, int);

typedef struct station_clip_s {
    aSTC_CHANGE_TALK_PROC change_talk_proc;
} aSTC_clip_c;

#ifdef __cplusplus
}
#endif

#endif
