#ifndef DATAOBJECT_H
#define DATAOBJECT_H

#include "types.h"

#ifdef __cplusplus
extern "C" {
#endif

// TODO: This file should be autogenerated.

extern u8 FONT_tex_font1[];
extern u8 FONT_tex_font2[];
extern u8 FONT_tex_font3[];
extern u8 FONT_tex_jyouge[];
extern u8 FONT_tex_sayuu[];
extern u8 FONT_tex_cursor[];
extern u8 FONT_tex_next[];
extern u8 FONT_tex_choice[];


extern u8 ef_wipe1_modelT[];
extern u8 ef_wipe2_modelT[];
extern u8 ef_wipe3_modelT[];



#ifdef __cplusplus
}
#endif

#endif
