#ifndef M_UMBRELLA_DEF_H
#define M_UMBRELLA_DEF_H

#include "types.h"

#ifdef __cplusplus
extern "C" {
#endif

#define UMBRELLA_START 0
#define UMBRELLA_00 (UMBRELLA_START + 0)
#define UMBRELLA_01 (UMBRELLA_START + 1)
#define UMBRELLA_02 (UMBRELLA_START + 2)
#define UMBRELLA_03 (UMBRELLA_START + 3)
#define UMBRELLA_04 (UMBRELLA_START + 4)
#define UMBRELLA_05 (UMBRELLA_START + 5)
#define UMBRELLA_06 (UMBRELLA_START + 6)
#define UMBRELLA_07 (UMBRELLA_START + 7)
#define UMBRELLA_08 (UMBRELLA_START + 8)
#define UMBRELLA_09 (UMBRELLA_START + 9)
#define UMBRELLA_10 (UMBRELLA_START + 10)
#define UMBRELLA_11 (UMBRELLA_START + 11)
#define UMBRELLA_12 (UMBRELLA_START + 12)
#define UMBRELLA_13 (UMBRELLA_START + 13)
#define UMBRELLA_14 (UMBRELLA_START + 14)
#define UMBRELLA_15 (UMBRELLA_START + 15)
#define UMBRELLA_16 (UMBRELLA_START + 16)
#define UMBRELLA_17 (UMBRELLA_START + 17)
#define UMBRELLA_18 (UMBRELLA_START + 18)
#define UMBRELLA_19 (UMBRELLA_START + 19)
#define UMBRELLA_20 (UMBRELLA_START + 20)
#define UMBRELLA_21 (UMBRELLA_START + 21)
#define UMBRELLA_22 (UMBRELLA_START + 22)
#define UMBRELLA_23 (UMBRELLA_START + 23)
#define UMBRELLA_24 (UMBRELLA_START + 24)
#define UMBRELLA_25 (UMBRELLA_START + 25)
#define UMBRELLA_26 (UMBRELLA_START + 26)
#define UMBRELLA_27 (UMBRELLA_START + 27)
#define UMBRELLA_28 (UMBRELLA_START + 28)
#define UMBRELLA_29 (UMBRELLA_START + 29)
#define UMBRELLA_30 (UMBRELLA_START + 30)
#define UMBRELLA_31 (UMBRELLA_START + 31)
#define UMBRELLA_END (UMBRELLA_START + 31)
#define UMBRELLA_MY_START (UMBRELLA_START + 32)
#define UMBRELLA_MY_00 (UMBRELLA_MY_START + 0)
#define UMBRELLA_MY_01 (UMBRELLA_MY_START + 1)
#define UMBRELLA_MY_02 (UMBRELLA_MY_START + 2)
#define UMBRELLA_MY_03 (UMBRELLA_MY_START + 3)
#define UMBRELLA_MY_04 (UMBRELLA_MY_START + 4)
#define UMBRELLA_MY_05 (UMBRELLA_MY_START + 5)
#define UMBRELLA_MY_06 (UMBRELLA_MY_START + 6)
#define UMBRELLA_MY_07 (UMBRELLA_MY_START + 7)
#define UMBRELLA_MY_END (UMBRELLA_MY_START + 7)
#define UMBRELLA_ALL_END (UMBRELLA_MY_END)

#define UMBRELLA_NUM ((UMBRELLA_END - UMBRELLA_START) + 1)
#define UMBRELLA_MY_NUM (UMBRELLA_MY_END - UMBRELLA_MY_START)
#define UMBRELLA_ALL_NUM (UMBRELLA_ALL_END - UMBRELLA_START)

#ifdef __cplusplus
}
#endif
#endif // M_UMBRELLA_DEF_H
