compiler_type = "mwcc"
compiler_command = "build/tools/wibo build/compilers/GC/1.2.5n/mwcceppc.exe -nodefaults -proc gekko -align powerpc -enum int -multibyte -char unsigned -fp hardware -Cpp_exceptions off -pragma 'cats off' -pragma 'warn_notinlined off' -maxerrors 1 -nosyspath -DVERSION=0 -DNDEBUG=1 -inline all -lang=c -Iinclude -Ilibc -c"
assembler_command = "powerpc-eabi-as -mgekko"
asm_prelude_file = "include/macros.inc"

[preserve_macros]
"NULL" = "void*"
"true" = "int"
"false" = "int"
"ALIGN_PREV" = "int"
"ALIGN_NEXT" = "int"
"ARRAY_COUNT" = "int"
"ARRAY_COUNTU" = "unsigned int"
"OFFSETOF" = "int"
